/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controler.connection;
import java.awt.List;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import java.util.Arrays;
import javax.swing.JOptionPane;
/**
 *
 * @author JUNAN
 */
public class dashboardUser extends javax.swing.JFrame {

    /**
     * Creates new form dashboard
     */
    public ArrayList<Integer> skTanahIds = new ArrayList<Integer>();
    public ArrayList<Integer> permohonanIds = new ArrayList<Integer>();
    
    public String activeUser;
    public int activeUserId;
    private int popUpNotif = 0;
    public dashboardUser(String nameUser,int idUser){
        initComponents();
        tampilDataPermohonan();
        this.activeUser = nameUser;
        this.activeUserId = idUser;
        nameUserActive.setText(this.activeUser);
        System.out.println("active user name " +this.activeUser);
        System.out.print("active user id pemohon " +this.activeUserId);
    }
    
    
    public dashboardUser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bodyPanel = new javax.swing.JPanel();
        sidebarPannel = new javax.swing.JPanel();
        btnHome = new javax.swing.JPanel();
        lblhome = new javax.swing.JLabel();
        btnPengukuran = new javax.swing.JPanel();
        lblPemetaan = new javax.swing.JLabel();
        btnSktanah = new javax.swing.JPanel();
        lblSktanah = new javax.swing.JLabel();
        btnAbout = new javax.swing.JLabel();
        btnLogout = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        btnExit = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        homePannel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        nameUserActive = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        step1 = new javax.swing.JLabel();
        ilustration1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btnCardAjukan = new javax.swing.JLabel();
        bgCard = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        step2 = new javax.swing.JLabel();
        ilustration2 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        btnCardUpload = new javax.swing.JLabel();
        bgCard1 = new javax.swing.JLabel();
        pemetaanPannel = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePemetaan = new javax.swing.JTable();
        btnSunting = new javax.swing.JLabel();
        btnRefresh = new javax.swing.JLabel();
        btnDetail = new javax.swing.JLabel();
        btnHasil = new javax.swing.JLabel();
        btnPermohonan = new javax.swing.JLabel();
        skTanahPannel = new javax.swing.JPanel();
        btnRefreshSkTanah = new javax.swing.JLabel();
        btnSuntingSK = new javax.swing.JLabel();
        btnPermohonanSk = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableSkTanah = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1074, 660));
        setUndecorated(true);
        setResizable(false);

        bodyPanel.setMinimumSize(new java.awt.Dimension(1074, 660));
        bodyPanel.setName(""); // NOI18N

        sidebarPannel.setBackground(new java.awt.Color(21, 28, 82));
        sidebarPannel.setPreferredSize(new java.awt.Dimension(319, 660));
        sidebarPannel.setRequestFocusEnabled(false);
        sidebarPannel.setVerifyInputWhenFocusTarget(false);

        btnHome.setBackground(new java.awt.Color(59, 79, 207));
        btnHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHome.setPreferredSize(new java.awt.Dimension(218, 59));
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHomeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnHomeMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnHomeMouseReleased(evt);
            }
        });
        btnHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblhome.setFont(new java.awt.Font("Montserrat Medium", 0, 18)); // NOI18N
        lblhome.setForeground(new java.awt.Color(241, 245, 248));
        lblhome.setText("Home");
        lblhome.setToolTipText("");
        lblhome.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblhome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblhomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblhomeMouseEntered(evt);
            }
        });
        btnHome.add(lblhome, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 17, -1, -1));

        btnPengukuran.setBackground(new java.awt.Color(30, 38, 95));
        btnPengukuran.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPengukuran.setPreferredSize(new java.awt.Dimension(218, 59));
        btnPengukuran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPengukuranMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPengukuranMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPengukuranMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPengukuranMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnPengukuranMouseReleased(evt);
            }
        });
        btnPengukuran.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPemetaan.setFont(new java.awt.Font("Montserrat Medium", 0, 18)); // NOI18N
        lblPemetaan.setForeground(new java.awt.Color(241, 245, 248));
        lblPemetaan.setText("Pemetaan");
        lblPemetaan.setToolTipText("");
        lblPemetaan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPemetaanMouseClicked(evt);
            }
        });
        btnPengukuran.add(lblPemetaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 17, -1, -1));

        btnSktanah.setBackground(new java.awt.Color(30, 38, 95));
        btnSktanah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSktanah.setPreferredSize(new java.awt.Dimension(218, 59));
        btnSktanah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSktanahMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSktanahMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSktanahMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSktanahMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnSktanahMouseReleased(evt);
            }
        });
        btnSktanah.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSktanah.setFont(new java.awt.Font("Montserrat Medium", 0, 18)); // NOI18N
        lblSktanah.setForeground(new java.awt.Color(241, 245, 248));
        lblSktanah.setText("SK Tanah");
        lblSktanah.setToolTipText("");
        lblSktanah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSktanahMouseClicked(evt);
            }
        });
        btnSktanah.add(lblSktanah, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 16, -1, -1));

        btnAbout.setBackground(new java.awt.Color(155, 156, 172));
        btnAbout.setFont(new java.awt.Font("Montserrat Medium", 0, 16)); // NOI18N
        btnAbout.setForeground(new java.awt.Color(155, 156, 172));
        btnAbout.setText("About");
        btnAbout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAbout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAboutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAboutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAboutMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAboutMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnAboutMouseReleased(evt);
            }
        });

        btnLogout.setFont(new java.awt.Font("Montserrat Medium", 0, 16)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(155, 156, 172));
        btnLogout.setText("Logout");
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLogoutMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnLogoutMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnLogoutMouseReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Montserrat Medium", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(155, 156, 172));
        jLabel4.setText(" |");

        jLabel7.setFont(new java.awt.Font("Montserrat", 1, 22)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(242, 242, 242));
        jLabel7.setText("BADAN");

        jLabel8.setFont(new java.awt.Font("Montserrat", 1, 22)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(242, 242, 242));
        jLabel8.setText("PERTANAHAN");

        jLabel9.setFont(new java.awt.Font("Montserrat", 1, 22)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(242, 242, 242));
        jLabel9.setText("NASIONAL BATAM");

        javax.swing.GroupLayout sidebarPannelLayout = new javax.swing.GroupLayout(sidebarPannel);
        sidebarPannel.setLayout(sidebarPannelLayout);
        sidebarPannelLayout.setHorizontalGroup(
            sidebarPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarPannelLayout.createSequentialGroup()
                .addGroup(sidebarPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sidebarPannelLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(sidebarPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(btnPengukuran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSktanah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(sidebarPannelLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(btnAbout)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLogout)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        sidebarPannelLayout.setVerticalGroup(
            sidebarPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarPannelLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnPengukuran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnSktanah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addGroup(sidebarPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAbout, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52))
        );

        jPanel2.setBackground(new java.awt.Color(241, 245, 248));
        jPanel2.setMinimumSize(new java.awt.Dimension(755, 660));
        jPanel2.setPreferredSize(new java.awt.Dimension(755, 660));
        jPanel2.setVerifyInputWhenFocusTarget(false);

        headerPanel.setBackground(new java.awt.Color(241, 245, 248));
        headerPanel.setPreferredSize(new java.awt.Dimension(755, 660));

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/closeBtn.png"))); // NOI18N
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExitMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnExitMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnExitMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        mainPanel.setBackground(new java.awt.Color(241, 245, 248));
        mainPanel.setPreferredSize(new java.awt.Dimension(755, 600));
        mainPanel.setLayout(new java.awt.CardLayout());

        homePannel.setBackground(new java.awt.Color(241, 245, 248));
        homePannel.setPreferredSize(new java.awt.Dimension(755, 600));

        jPanel1.setBackground(new java.awt.Color(232, 237, 248));
        jPanel1.setMinimumSize(new java.awt.Dimension(755, 102));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(755, 102));

        jLabel5.setFont(new java.awt.Font("Montserrat Medium", 1, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(83, 87, 122));
        jLabel5.setText("Welcome");

        nameUserActive.setFont(new java.awt.Font("Montserrat Medium", 1, 30)); // NOI18N
        nameUserActive.setForeground(new java.awt.Color(83, 87, 122));
        nameUserActive.setText("User1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nameUserActive)
                .addContainerGap(472, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(nameUserActive))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        step1.setFont(new java.awt.Font("Montserrat SemiBold", 0, 13)); // NOI18N
        step1.setForeground(new java.awt.Color(120, 122, 145));
        step1.setText("Step 1");
        jPanel3.add(step1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, -1));

        ilustration1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/cardStepIlustration1.png"))); // NOI18N
        jPanel3.add(ilustration1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel6.setFont(new java.awt.Font("Montserrat Medium", 0, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(120, 122, 145));
        jLabel6.setText("Pengajuan permohonan untuk");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 210, 30));

        jLabel12.setFont(new java.awt.Font("Montserrat Medium", 0, 13)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(120, 122, 145));
        jLabel12.setText("pengukuran tanah anda miliki,");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 210, 30));

        jLabel13.setFont(new java.awt.Font("Montserrat Medium", 0, 13)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(120, 122, 145));
        jLabel13.setText("agar surat ukur dapat di proses");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 220, 30));

        jLabel14.setFont(new java.awt.Font("Montserrat Medium", 0, 13)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(120, 122, 145));
        jLabel14.setText("untuk tahap selanjutnya");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 210, 30));

        jLabel1.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ajukan");
        jLabel1.setToolTipText("");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 50, 20));

        jPanel5.setOpaque(false);

        btnCardAjukan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/buttonCard.png"))); // NOI18N
        btnCardAjukan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCardAjukanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCardAjukanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCardAjukanMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCardAjukanMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnCardAjukanMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCardAjukan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCardAjukan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 90, 40));

        bgCard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/cardStep.png"))); // NOI18N
        bgCard.setToolTipText("");
        jPanel3.add(bgCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, -1));

        jPanel6.setOpaque(false);
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        step2.setFont(new java.awt.Font("Montserrat SemiBold", 0, 13)); // NOI18N
        step2.setForeground(new java.awt.Color(120, 122, 145));
        step2.setText("Step 2");
        jPanel6.add(step2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, -1));

        ilustration2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/cardStepIlustration2.png"))); // NOI18N
        jPanel6.add(ilustration2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        jLabel15.setFont(new java.awt.Font("Montserrat Medium", 0, 13)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(120, 122, 145));
        jLabel15.setText("Silahkan upload kembali surat ");
        jPanel6.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 210, 20));

        jLabel16.setFont(new java.awt.Font("Montserrat Medium", 0, 13)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(120, 122, 145));
        jLabel16.setText("ukur berserta dokumen lainnya ");
        jPanel6.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 220, 20));

        jLabel17.setFont(new java.awt.Font("Montserrat Medium", 0, 13)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(120, 122, 145));
        jLabel17.setText("untuk pengajuan SK kuasa ");
        jPanel6.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 220, 20));

        jLabel18.setFont(new java.awt.Font("Montserrat Medium", 0, 13)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(120, 122, 145));
        jLabel18.setText("tanah");
        jPanel6.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 210, 20));

        jLabel3.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Upload");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel6.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 50, 20));

        jPanel7.setOpaque(false);

        btnCardUpload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/buttonCard.png"))); // NOI18N
        btnCardUpload.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCardUploadMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCardUploadMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCardUploadMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCardUploadMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnCardUploadMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCardUpload, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCardUpload, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel6.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 90, 40));

        bgCard1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/cardStep.png"))); // NOI18N
        bgCard1.setToolTipText("");
        jPanel6.add(bgCard1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, -1));

        javax.swing.GroupLayout homePannelLayout = new javax.swing.GroupLayout(homePannel);
        homePannel.setLayout(homePannelLayout);
        homePannelLayout.setHorizontalGroup(
            homePannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(homePannelLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        homePannelLayout.setVerticalGroup(
            homePannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePannelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addGroup(homePannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        mainPanel.add(homePannel, "card2");

        pemetaanPannel.setBackground(new java.awt.Color(241, 245, 248));

        jPanel4.setBackground(new java.awt.Color(232, 237, 248));
        jPanel4.setMinimumSize(new java.awt.Dimension(755, 102));
        jPanel4.setName(""); // NOI18N

        jLabel20.setFont(new java.awt.Font("Montserrat Medium", 1, 30)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(83, 87, 122));
        jLabel20.setText("Pemetaan");

        jLabel21.setFont(new java.awt.Font("Montserrat Medium", 0, 13)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(120, 122, 145));
        jLabel21.setText("Hasil surat ukur akan di berikan setelah petugas berangkat ke lokasi");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(jLabel20))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addGap(0, 0, 0)
                .addComponent(jLabel21)
                .addGap(20, 20, 20))
        );

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));

        tablePemetaan.setBackground(new java.awt.Color(255, 255, 255));
        tablePemetaan.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        tablePemetaan.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        tablePemetaan.setForeground(new java.awt.Color(122, 124, 147));
        tablePemetaan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"01", "23124556", "Batam center", "verified"},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "NO", "NIK", "LOKASI", "STATUS"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tablePemetaan.setGridColor(new java.awt.Color(255, 255, 255));
        tablePemetaan.setRowHeight(35);
        tablePemetaan.setSelectionBackground(new java.awt.Color(71, 86, 119));
        tablePemetaan.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tablePemetaan.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tablePemetaan);
        if (tablePemetaan.getColumnModel().getColumnCount() > 0) {
            tablePemetaan.getColumnModel().getColumn(0).setResizable(false);
            tablePemetaan.getColumnModel().getColumn(0).setPreferredWidth(3);
            tablePemetaan.getColumnModel().getColumn(1).setResizable(false);
            tablePemetaan.getColumnModel().getColumn(1).setPreferredWidth(5);
            tablePemetaan.getColumnModel().getColumn(2).setResizable(false);
            tablePemetaan.getColumnModel().getColumn(2).setPreferredWidth(10);
            tablePemetaan.getColumnModel().getColumn(3).setResizable(false);
        }

        btnSunting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/btnSunting.png"))); // NOI18N
        btnSunting.setToolTipText("");
        btnSunting.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSunting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSuntingMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSuntingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSuntingMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSuntingMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnSuntingMouseReleased(evt);
            }
        });

        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/btnRefresh.png"))); // NOI18N
        btnRefresh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRefresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRefreshMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRefreshMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRefreshMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnRefreshMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnRefreshMouseReleased(evt);
            }
        });

        btnDetail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/btnDetail.png"))); // NOI18N
        btnDetail.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDetail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDetailMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDetailMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDetailMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnDetailMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnDetailMouseReleased(evt);
            }
        });

        btnHasil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/btnHasil.png"))); // NOI18N
        btnHasil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHasil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHasilMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHasilMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHasilMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnHasilMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnHasilMouseReleased(evt);
            }
        });

        btnPermohonan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/btnPermohonan.png"))); // NOI18N
        btnPermohonan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPermohonan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPermohonanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPermohonanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPermohonanMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPermohonanMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnPermohonanMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout pemetaanPannelLayout = new javax.swing.GroupLayout(pemetaanPannel);
        pemetaanPannel.setLayout(pemetaanPannelLayout);
        pemetaanPannelLayout.setHorizontalGroup(
            pemetaanPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pemetaanPannelLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(pemetaanPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pemetaanPannelLayout.createSequentialGroup()
                        .addComponent(btnRefresh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSunting)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDetail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHasil)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPermohonan)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        pemetaanPannelLayout.setVerticalGroup(
            pemetaanPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pemetaanPannelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pemetaanPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pemetaanPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnHasil)
                        .addComponent(btnRefresh, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnDetail))
                    .addComponent(btnSunting)
                    .addComponent(btnPermohonan))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        mainPanel.add(pemetaanPannel, "card3");

        skTanahPannel.setBackground(new java.awt.Color(241, 245, 248));

        btnRefreshSkTanah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/btnRefresh.png"))); // NOI18N
        btnRefreshSkTanah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRefreshSkTanah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRefreshSkTanahMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRefreshSkTanahMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRefreshSkTanahMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnRefreshSkTanahMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnRefreshSkTanahMouseReleased(evt);
            }
        });

        btnSuntingSK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/btnSunting.png"))); // NOI18N
        btnSuntingSK.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSuntingSK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSuntingSKMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSuntingSKMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSuntingSKMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSuntingSKMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnSuntingSKMouseReleased(evt);
            }
        });

        btnPermohonanSk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/btnPermohonan.png"))); // NOI18N
        btnPermohonanSk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPermohonanSk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPermohonanSkMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPermohonanSkMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPermohonanSkMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPermohonanSkMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnPermohonanSkMouseReleased(evt);
            }
        });

        jPanel8.setBackground(new java.awt.Color(232, 237, 248));
        jPanel8.setMinimumSize(new java.awt.Dimension(755, 102));
        jPanel8.setName(""); // NOI18N

        jLabel22.setFont(new java.awt.Font("Montserrat Medium", 1, 30)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(83, 87, 122));
        jLabel22.setText("Surat Kuasa Tanah");

        jLabel23.setFont(new java.awt.Font("Montserrat Medium", 0, 13)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(120, 122, 145));
        jLabel23.setText("Pastikan anda telah melakukan anda telah melewati tahap pengukuran");

        jLabel24.setFont(new java.awt.Font("Montserrat Medium", 0, 13)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(120, 122, 145));
        jLabel24.setText("dan mendapatkan surat hasil ukur");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(jLabel23)
                    .addComponent(jLabel22))
                .addContainerGap(233, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel23)
                .addGap(0, 0, 0)
                .addComponent(jLabel24)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jScrollPane3.setForeground(new java.awt.Color(255, 255, 255));

        tableSkTanah.setBackground(new java.awt.Color(255, 255, 255));
        tableSkTanah.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        tableSkTanah.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        tableSkTanah.setForeground(new java.awt.Color(122, 124, 147));
        tableSkTanah.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"01", "dok1.png", "dok2.png", "dok3.png", "Pemeriksaan"},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "NO", "Dokumen 1", "Dokumen 2", "Dokumen 3", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableSkTanah.setGridColor(new java.awt.Color(255, 255, 255));
        tableSkTanah.setRowHeight(35);
        tableSkTanah.setSelectionBackground(new java.awt.Color(71, 86, 119));
        tableSkTanah.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tableSkTanah.getTableHeader().setReorderingAllowed(false);
        tableSkTanah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableSkTanahMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tableSkTanah);
        if (tableSkTanah.getColumnModel().getColumnCount() > 0) {
            tableSkTanah.getColumnModel().getColumn(0).setResizable(false);
            tableSkTanah.getColumnModel().getColumn(0).setPreferredWidth(3);
            tableSkTanah.getColumnModel().getColumn(1).setResizable(false);
            tableSkTanah.getColumnModel().getColumn(1).setPreferredWidth(5);
            tableSkTanah.getColumnModel().getColumn(2).setResizable(false);
            tableSkTanah.getColumnModel().getColumn(2).setPreferredWidth(10);
            tableSkTanah.getColumnModel().getColumn(3).setResizable(false);
            tableSkTanah.getColumnModel().getColumn(4).setResizable(false);
        }

        javax.swing.GroupLayout skTanahPannelLayout = new javax.swing.GroupLayout(skTanahPannel);
        skTanahPannel.setLayout(skTanahPannelLayout);
        skTanahPannelLayout.setHorizontalGroup(
            skTanahPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(skTanahPannelLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(skTanahPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(skTanahPannelLayout.createSequentialGroup()
                        .addComponent(btnRefreshSkTanah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSuntingSK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPermohonanSk))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        skTanahPannelLayout.setVerticalGroup(
            skTanahPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, skTanahPannelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(skTanahPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSuntingSK)
                    .addComponent(btnPermohonanSk)
                    .addComponent(btnRefreshSkTanah))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        mainPanel.add(skTanahPannel, "card4");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout bodyPanelLayout = new javax.swing.GroupLayout(bodyPanel);
        bodyPanel.setLayout(bodyPanelLayout);
        bodyPanelLayout.setHorizontalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyPanelLayout.createSequentialGroup()
                .addComponent(sidebarPannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        bodyPanelLayout.setVerticalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidebarPannel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    
    //Behavior BtnHome
    private void btnHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseEntered
//        // TODO add your handling code here:
//         btnHome.setBackground(new java.awt.Color(39,49,118));
    }//GEN-LAST:event_btnHomeMouseEntered

    private void btnHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseExited
        // TODO add your handling code here:
//         btnHome.setBackground(new java.awt.Color(39,49,118));
//         btnHome.setBackground(new java.awt.Color(30,38,95));
    }//GEN-LAST:event_btnHomeMouseExited

    private void btnHomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMousePressed
        // TODO add your handling code here:
         btnHome.setBackground(new java.awt.Color(45,57,132));
    }//GEN-LAST:event_btnHomeMousePressed

    private void btnHomeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseReleased
        // TODO add your handling code here:
         btnHome.setBackground(new java.awt.Color(30,38,95));
    }//GEN-LAST:event_btnHomeMouseReleased

    private void btnHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseClicked
        // TODO add your handling code here:
        btnHome.setBackground(new java.awt.Color(59,79,207));
        btnPengukuran.setBackground(new java.awt.Color(30,38,95));
        btnSktanah.setBackground(new java.awt.Color(30,38,95));
        
        
        //panel swap
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        mainPanel.add(homePannel);
        mainPanel.repaint();
        mainPanel.revalidate();
        
        
    }//GEN-LAST:event_btnHomeMouseClicked

    
    
    
    //Behavior btnPengukuran
    private void btnPengukuranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPengukuranMouseClicked
        // TODO add your handling code here:
        btnPengukuran.setBackground(new java.awt.Color(59,79,207));
        btnHome.setBackground(new java.awt.Color(30,38,95));
        btnSktanah.setBackground(new java.awt.Color(30,38,95));
        
        //panel swap
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        mainPanel.add(pemetaanPannel);
        tampilDataPermohonan();
        mainPanel.repaint();
        mainPanel.revalidate();
        
    }//GEN-LAST:event_btnPengukuranMouseClicked

    private void btnPengukuranMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPengukuranMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPengukuranMouseEntered

    private void btnPengukuranMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPengukuranMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPengukuranMouseExited

    private void btnPengukuranMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPengukuranMousePressed
        // TODO add your handling code here:
         btnPengukuran.setBackground(new java.awt.Color(45,57,132));
    }//GEN-LAST:event_btnPengukuranMousePressed

    private void btnPengukuranMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPengukuranMouseReleased
        // TODO add your handling code here:
         btnPengukuran.setBackground(new java.awt.Color(30,38,95));
    }//GEN-LAST:event_btnPengukuranMouseReleased

    
    //Behavior btnSktanah
    private void btnSktanahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSktanahMouseClicked
        // TODO add your handling code here:
        btnSktanah.setBackground(new java.awt.Color(59,79,207));
        btnHome.setBackground(new java.awt.Color(30,38,95));
        btnPengukuran.setBackground(new java.awt.Color(30,38,95));
        
          //panel swap
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        mainPanel.add(skTanahPannel);
        tampilDataSkTanah();
        
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btnSktanahMouseClicked

    private void btnSktanahMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSktanahMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSktanahMouseEntered

    private void btnSktanahMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSktanahMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSktanahMouseExited

    private void btnSktanahMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSktanahMousePressed
        // TODO add your handling code here:
         btnSktanah.setBackground(new java.awt.Color(45,57,132));
    }//GEN-LAST:event_btnSktanahMousePressed

    private void btnSktanahMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSktanahMouseReleased
        // TODO add your handling code here:
        btnSktanah.setBackground(new java.awt.Color(30,38,95));
    }//GEN-LAST:event_btnSktanahMouseReleased

    
    
//    behavior btnLogout
    private void btnLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseEntered
        // TODO add your handling code here:
        btnLogout.setForeground(new java.awt.Color(217,218,222));
    }//GEN-LAST:event_btnLogoutMouseEntered

    private void btnLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseExited
        // TODO add your handling code here:
        btnLogout.setForeground(new java.awt.Color(155,156,172));
    }//GEN-LAST:event_btnLogoutMouseExited

    private void btnLogoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMousePressed
        // TODO add your handling code here:
         btnLogout.setForeground(new java.awt.Color(240,240,241));
    }//GEN-LAST:event_btnLogoutMousePressed

    private void btnLogoutMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseReleased
        // TODO add your handling code here:
         btnLogout.setForeground(new java.awt.Color(155,156,172));
    }//GEN-LAST:event_btnLogoutMouseReleased

    
//    behavior btnAbout
    private void btnAboutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAboutMouseEntered
        // TODO add your handling code here:
        btnAbout.setForeground(new java.awt.Color(217,218,222));
    }//GEN-LAST:event_btnAboutMouseEntered

    private void btnAboutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAboutMouseExited
        // TODO add your handling code here:
        btnAbout.setForeground(new java.awt.Color(155,156,172));
    }//GEN-LAST:event_btnAboutMouseExited

    private void btnAboutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAboutMousePressed
        // TODO add your handling code here:
        btnAbout.setForeground(new java.awt.Color(240,240,241));
    }//GEN-LAST:event_btnAboutMousePressed

    private void btnAboutMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAboutMouseReleased
        // TODO add your handling code here:
        btnAbout.setForeground(new java.awt.Color(155,156,172));
    }//GEN-LAST:event_btnAboutMouseReleased

    
     //behavior btn ajukan
    private void btnCardAjukanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCardAjukanMouseEntered
        // TODO add your handling code here:
         btnCardAjukan.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/buttonCardHover.png")));
    }//GEN-LAST:event_btnCardAjukanMouseEntered

    private void btnCardAjukanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCardAjukanMouseExited
        // TODO add your handling code here:
        btnCardAjukan.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/buttonCard.png")));
    }//GEN-LAST:event_btnCardAjukanMouseExited

    private void btnCardAjukanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCardAjukanMousePressed
        // TODO add your handling code here:
        btnCardAjukan.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/buttonCardPress.png")));
    }//GEN-LAST:event_btnCardAjukanMousePressed

    private void btnCardAjukanMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCardAjukanMouseReleased
        // TODO add your handling code here:
        btnCardAjukan.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/buttonCard.png")));
    }//GEN-LAST:event_btnCardAjukanMouseReleased

    
    //behavior btn upload
    private void btnCardUploadMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCardUploadMouseEntered
        // TODO add your handling code here:
        btnCardUpload.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/buttonCardHover.png")));
    }//GEN-LAST:event_btnCardUploadMouseEntered

    private void btnCardUploadMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCardUploadMouseExited
        // TODO add your handling code here:
       btnCardUpload.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/buttonCard.png")));
    }//GEN-LAST:event_btnCardUploadMouseExited

    private void btnCardUploadMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCardUploadMousePressed
        // TODO add your handling code here:
        btnCardUpload.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/buttonCardPress.png")));
    }//GEN-LAST:event_btnCardUploadMousePressed

    private void btnCardUploadMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCardUploadMouseReleased
        // TODO add your handling code here:
        btnCardUpload.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/buttonCard.png")));
    }//GEN-LAST:event_btnCardUploadMouseReleased

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExitMouseClicked

    private void btnExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseEntered
        // TODO add your handling code here:
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/closeBtnHover.png")));
    }//GEN-LAST:event_btnExitMouseEntered

    private void btnExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseExited
        // TODO add your handling code here:
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/closeBtn.png")));
    }//GEN-LAST:event_btnExitMouseExited

    private void btnExitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMousePressed
        // TODO add your handling code here:
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/closeBtnPressed.png")));
    }//GEN-LAST:event_btnExitMousePressed

    private void btnExitMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseReleased
        // TODO add your handling code here:
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/closeBtn.png")));
    }//GEN-LAST:event_btnExitMouseReleased

    
    //behavior btnSunting
    private void btnSuntingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuntingMouseEntered
        // TODO add your handling code here:
          btnSunting.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/btnSuntingHover.png")));
    }//GEN-LAST:event_btnSuntingMouseEntered

    private void btnSuntingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuntingMouseExited
        // TODO add your handling code here:
         btnSunting.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/btnSunting.png")));
    }//GEN-LAST:event_btnSuntingMouseExited

    private void btnSuntingMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuntingMousePressed
        // TODO add your handling code here:
         btnSunting.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/btnSuntingPress.png")));
    }//GEN-LAST:event_btnSuntingMousePressed

    private void btnSuntingMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuntingMouseReleased
        // TODO add your handling code here:
         btnSunting.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/btnSunting.png")));
    }//GEN-LAST:event_btnSuntingMouseReleased

    
    
    //behavior btnDetail
    private void btnDetailMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDetailMouseEntered
        // TODO add your handling code here:
          btnDetail.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/btnDetailHover.png")));
    }//GEN-LAST:event_btnDetailMouseEntered

    private void btnDetailMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDetailMouseExited
        // TODO add your handling code here:
          btnDetail.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/btnDetail.png")));
    }//GEN-LAST:event_btnDetailMouseExited

    private void btnDetailMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDetailMousePressed
        // TODO add your handling code here:
         btnDetail.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/btnDetailPress.png")));
    }//GEN-LAST:event_btnDetailMousePressed

    private void btnDetailMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDetailMouseReleased
        // TODO add your handling code here:
         btnDetail.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/btnDetail.png")));
    }//GEN-LAST:event_btnDetailMouseReleased

    
    //behavior btnHasil
    private void btnHasilMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHasilMouseEntered
        // TODO add your handling code here:
        btnHasil.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/btnHasilHover.png")));
    }//GEN-LAST:event_btnHasilMouseEntered

    private void btnHasilMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHasilMouseExited
        // TODO add your handling code here:
        btnHasil.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/btnHasil.png")));
    }//GEN-LAST:event_btnHasilMouseExited

    private void btnHasilMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHasilMousePressed
        // TODO add your handling code here:
         btnHasil.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/btnHasilPress.png")));
    }//GEN-LAST:event_btnHasilMousePressed

    private void btnHasilMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHasilMouseReleased
        // TODO add your handling code here:
         btnHasil.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/btnHasil.png")));
    }//GEN-LAST:event_btnHasilMouseReleased

//    behavior btnPermohonan
    private void btnPermohonanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPermohonanMouseEntered
        // TODO add your handling code here:
         btnPermohonan.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/btnPermohonanHover.png")));
    }//GEN-LAST:event_btnPermohonanMouseEntered

    private void btnPermohonanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPermohonanMouseExited
        // TODO add your handling code here:
        btnPermohonan.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/btnPermohonan.png")));
    }//GEN-LAST:event_btnPermohonanMouseExited

    private void btnPermohonanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPermohonanMousePressed
        // TODO add your handling code here:
        btnPermohonan.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/btnPermohonanPress.png")));
    }//GEN-LAST:event_btnPermohonanMousePressed

    private void btnPermohonanMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPermohonanMouseReleased
        // TODO add your handling code here:
          btnPermohonan.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/btnPermohonan.png")));
    }//GEN-LAST:event_btnPermohonanMouseReleased

    private void btnSuntingSKMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuntingSKMouseEntered
        // TODO add your handling code here:
        btnSuntingSK.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/btnSuntingHover.png")));
    }//GEN-LAST:event_btnSuntingSKMouseEntered

    private void btnSuntingSKMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuntingSKMouseExited
        // TODO add your handling code here:
        btnSuntingSK.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/btnSunting.png")));
    }//GEN-LAST:event_btnSuntingSKMouseExited

    private void btnSuntingSKMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuntingSKMousePressed
        // TODO add your handling code here:
        btnSuntingSK.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/btnSuntingPress.png")));
    }//GEN-LAST:event_btnSuntingSKMousePressed

    private void btnSuntingSKMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuntingSKMouseReleased
        // TODO add your handling code here:
        btnSuntingSK.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/btnSunting.png")));
    }//GEN-LAST:event_btnSuntingSKMouseReleased

    
    
    private void btnPermohonanSkMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPermohonanSkMouseEntered
        // TODO add your handling code here:
        btnPermohonanSk.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/btnPermohonanHover.png")));
    }//GEN-LAST:event_btnPermohonanSkMouseEntered

    private void btnPermohonanSkMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPermohonanSkMouseExited
        // TODO add your handling code here:
         btnPermohonanSk.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/btnPermohonan.png")));
    }//GEN-LAST:event_btnPermohonanSkMouseExited

    private void btnPermohonanSkMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPermohonanSkMousePressed
        // TODO add your handling code here:
         btnPermohonanSk.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/btnPermohonanPress.png")));
    }//GEN-LAST:event_btnPermohonanSkMousePressed

    private void btnPermohonanSkMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPermohonanSkMouseReleased
        // TODO add your handling code here:
         btnPermohonanSk.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/btnPermohonan.png")));
    }//GEN-LAST:event_btnPermohonanSkMouseReleased

    private void btnLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new login().setVisible(true);
    }//GEN-LAST:event_btnLogoutMouseClicked

    private void btnCardAjukanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCardAjukanMouseClicked
        // TODO add your handling code here:
        formPermohonanPengukuran form = new formPermohonanPengukuran(this.activeUser,this.activeUserId );
        form.setVisible(true);
    }//GEN-LAST:event_btnCardAjukanMouseClicked

    private void btnPermohonanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPermohonanMouseClicked
        // TODO add your handling code here:
        formPermohonanPengukuran form = new formPermohonanPengukuran(this.activeUser,this.activeUserId );
        form.setVisible(true);
    }//GEN-LAST:event_btnPermohonanMouseClicked

    private void lblhomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblhomeMouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_lblhomeMouseEntered

    private void lblhomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblhomeMouseClicked
        // TODO add your handling code here:
        btnHome.setBackground(new java.awt.Color(59,79,207));
        btnPengukuran.setBackground(new java.awt.Color(30,38,95));
        btnSktanah.setBackground(new java.awt.Color(30,38,95));
        
        
        //panel swap
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        mainPanel.add(homePannel);
        mainPanel.repaint();
        mainPanel.revalidate();
        
    }//GEN-LAST:event_lblhomeMouseClicked

    private void lblPemetaanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPemetaanMouseClicked
        // TODO add your handling code here:
        btnPengukuran.setBackground(new java.awt.Color(59,79,207));
        btnHome.setBackground(new java.awt.Color(30,38,95));
        btnSktanah.setBackground(new java.awt.Color(30,38,95));
        
        //panel swap
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        mainPanel.add(pemetaanPannel);
        tampilDataPermohonan();
        mainPanel.repaint();
        mainPanel.revalidate();
        
    }//GEN-LAST:event_lblPemetaanMouseClicked

    private void lblSktanahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSktanahMouseClicked
        // TODO add your handling code here:
        btnSktanah.setBackground(new java.awt.Color(59,79,207));
        btnHome.setBackground(new java.awt.Color(30,38,95));
        btnPengukuran.setBackground(new java.awt.Color(30,38,95));
        
          //panel swap
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        mainPanel.add(skTanahPannel);
        tampilDataSkTanah();
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_lblSktanahMouseClicked

    private void btnCardUploadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCardUploadMouseClicked
        // TODO add your handling code here:
         formPengajuanSK form = new formPengajuanSK(activeUser,activeUserId);
        form.setVisible(true);
    }//GEN-LAST:event_btnCardUploadMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
         formPermohonanPengukuran form = new formPermohonanPengukuran(this.activeUser,this.activeUserId );
        form.setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void btnPermohonanSkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPermohonanSkMouseClicked
        // TODO add your handling code here:
        formPengajuanSK form = new formPengajuanSK( activeUser,activeUserId);
        form.setVisible(true);
    }//GEN-LAST:event_btnPermohonanSkMouseClicked

    private void btnSuntingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuntingMouseClicked
        // TODO add your handling code here:
        
       if(tablePemetaan.getSelectionModel().isSelectionEmpty()){
           
           JOptionPane.showMessageDialog(this, "Harap Pilih baris berkas yang ingin anda sunting","Eror", JOptionPane.WARNING_MESSAGE);
       }else{
           SuntingFormPermohonanPengukuran form = new SuntingFormPermohonanPengukuran(permohonanIds.get(tablePemetaan.getSelectedRow()));
        form.setVisible(true);
       }
       
        
        
        
        
    }//GEN-LAST:event_btnSuntingMouseClicked

    private void btnHasilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHasilMouseClicked
        // TODO add your handling code here:
        
        int selectedRow = tablePemetaan.getSelectedRow();
        String result = tablePemetaan.getValueAt(selectedRow, 3).toString();
        
        
        
        
         if(tablePemetaan.getSelectionModel().isSelectionEmpty()){
            JOptionPane.showMessageDialog(this, "Harap Pilih baris berkas yang ingin anda tampilkan","Eror", JOptionPane.WARNING_MESSAGE);
         }else{   
              if(result.equals("Pengukuran Selesai")){
             viewHasilPengukuran vw = new viewHasilPengukuran(permohonanIds.get(tablePemetaan.getSelectedRow()));
             vw.setVisible(true);
              }else{
                  dialogNotFound nf = new dialogNotFound();
                  nf.setVisible(true);
            
              }
              
        }
             
        
    }//GEN-LAST:event_btnHasilMouseClicked

    private void btnDetailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDetailMouseClicked
        // TODO add your handling code here:
         if(tablePemetaan.getSelectionModel().isSelectionEmpty()){
            JOptionPane.showMessageDialog(this, "Harap Pilih baris berkas yang ingin anda tampilkan","Eror", JOptionPane.WARNING_MESSAGE);
         }else{
            viewTablePermohonan view = new viewTablePermohonan(permohonanIds.get(tablePemetaan.getSelectedRow()));
             view.setVisible(true);}
    }//GEN-LAST:event_btnDetailMouseClicked

    private void btnRefreshMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRefreshMouseReleased
        // TODO add your handling code here:
        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/btnRefresh.png")));
    }//GEN-LAST:event_btnRefreshMouseReleased

    private void btnRefreshMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRefreshMousePressed
        // TODO add your handling code here:
        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/btnRefreshPress.png")));
    }//GEN-LAST:event_btnRefreshMousePressed

    private void btnRefreshMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRefreshMouseExited
        // TODO add your handling code here:
        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/btnRefresh.png")));
    }//GEN-LAST:event_btnRefreshMouseExited

    //behavior btnHapus
    private void btnRefreshMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRefreshMouseEntered
        // TODO add your handling code here:
        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/btnRefreshHover.png")));
    }//GEN-LAST:event_btnRefreshMouseEntered

    private void btnRefreshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRefreshMouseClicked
        // TODO add your handling code here:
        tampilDataPermohonan();
    }//GEN-LAST:event_btnRefreshMouseClicked

    private void btnSuntingSKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuntingSKMouseClicked
        // TODO add your handling code here:
        if(tableSkTanah.getSelectionModel().isSelectionEmpty()){
        JOptionPane.showMessageDialog(this, "Harap Pilih baris berkas yang ingin anda sunting","Eror", JOptionPane.WARNING_MESSAGE);
        }else{
        SuntingFormPengajuanSKtanah sunting = new SuntingFormPengajuanSKtanah(skTanahIds.get(tableSkTanah.getSelectedRow()));
         sunting.setVisible(true);
                 }
    }//GEN-LAST:event_btnSuntingSKMouseClicked

    private void btnRefreshSkTanahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRefreshSkTanahMouseClicked
        // TODO add your handling code here:
        
        tampilDataSkTanah();
    }//GEN-LAST:event_btnRefreshSkTanahMouseClicked

    private void btnRefreshSkTanahMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRefreshSkTanahMouseEntered
        // TODO add your handling code here:
        btnRefreshSkTanah.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/btnRefreshHover.png")));
    }//GEN-LAST:event_btnRefreshSkTanahMouseEntered

    private void btnRefreshSkTanahMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRefreshSkTanahMouseExited
        // TODO add your handling code here:
        btnRefreshSkTanah.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/btnRefresh.png")));
    }//GEN-LAST:event_btnRefreshSkTanahMouseExited

    private void btnRefreshSkTanahMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRefreshSkTanahMousePressed
        // TODO add your handling code here:
        btnRefreshSkTanah.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/btnRefreshPress.png")));
    }//GEN-LAST:event_btnRefreshSkTanahMousePressed

    private void btnRefreshSkTanahMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRefreshSkTanahMouseReleased
        // TODO add your handling code here:
        btnRefreshSkTanah.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/btnRefresh.png")));
    }//GEN-LAST:event_btnRefreshSkTanahMouseReleased

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        formPengajuanSK form = new formPengajuanSK(activeUser,activeUserId);
        form.setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void btnAboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAboutMouseClicked
        // TODO add your handling code here:
        about abt = new about();
        abt.setVisible(true);
    }//GEN-LAST:event_btnAboutMouseClicked

    private void tableSkTanahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableSkTanahMouseClicked
        // TODO add your handling code here:
        int selectedRow = tableSkTanah.getSelectedRow();
        String result = tableSkTanah.getValueAt(selectedRow, 4).toString();
        
        if(result.equals("SK Diterbitkan")){
        dialogDone done = new dialogDone();
        done.setVisible(true);
        }
    }//GEN-LAST:event_tableSkTanahMouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboardUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboardUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboardUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboardUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboardUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgCard;
    private javax.swing.JLabel bgCard1;
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JLabel btnAbout;
    private javax.swing.JLabel btnCardAjukan;
    private javax.swing.JLabel btnCardUpload;
    private javax.swing.JLabel btnDetail;
    private javax.swing.JLabel btnExit;
    private javax.swing.JLabel btnHasil;
    private javax.swing.JPanel btnHome;
    private javax.swing.JLabel btnLogout;
    private javax.swing.JPanel btnPengukuran;
    private javax.swing.JLabel btnPermohonan;
    private javax.swing.JLabel btnPermohonanSk;
    private javax.swing.JLabel btnRefresh;
    private javax.swing.JLabel btnRefreshSkTanah;
    private javax.swing.JPanel btnSktanah;
    private javax.swing.JLabel btnSunting;
    private javax.swing.JLabel btnSuntingSK;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JPanel homePannel;
    private javax.swing.JLabel ilustration1;
    private javax.swing.JLabel ilustration2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblPemetaan;
    private javax.swing.JLabel lblSktanah;
    private javax.swing.JLabel lblhome;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel nameUserActive;
    private javax.swing.JPanel pemetaanPannel;
    private javax.swing.JPanel sidebarPannel;
    private javax.swing.JPanel skTanahPannel;
    private javax.swing.JLabel step1;
    private javax.swing.JLabel step2;
    private javax.swing.JTable tablePemetaan;
    private javax.swing.JTable tableSkTanah;
    // End of variables declaration//GEN-END:variables

    
    
    
    private void tampilDataPermohonan() {
     permohonanIds.clear();
    try{
    String query = "SELECT * FROM `db_bapena`.`tb_permohonan` INNER JOIN `db_bapena`.`tb_status` ON (`tb_permohonan`.`status` = `tb_status`.`id`) WHERE id_user = '"+activeUserId+"';" ;   
    
    java.sql.Connection conn = (Connection)connection.connectionDB();
    Statement st = conn.createStatement();
    ResultSet rs = st.executeQuery(query);
    
    if(rs.next() == false){
        btnSunting.setVisible(false);
        btnDetail.setVisible(false);
        btnHasil.setVisible(false);
    DefaultTableModel model = new DefaultTableModel();
    model.getDataVector().removeAllElements();
    model.fireTableDataChanged();
    model.setRowCount(0);
    
   
    model.addColumn("NO");
    model.addColumn("NIK");
    model.addColumn("ALAMAT");
    model.addColumn("STATUS");
     Object[] data = {
         "-" ,
         "-",
         "-",
         "-",
        };
        model.addRow(data);
        tablePemetaan.setModel(model);
    }else{
        btnSunting.setVisible(true);
        btnDetail.setVisible(true);
        btnHasil.setVisible(true);
        
        DefaultTableModel model = new DefaultTableModel();
    model.getDataVector().removeAllElements();
    model.fireTableDataChanged();
    model.setRowCount(0);
    
   
    model.addColumn("NO");
    model.addColumn("NIK");
    model.addColumn("ALAMAT");
    model.addColumn("STATUS");
    int no =1;
    do{
     permohonanIds.add(rs.getInt("idPermohonan"));
        Object[] data = {
         no++ ,
         rs.getString("nik"),
         rs.getString("alamat"),
         rs.getString("nama_status"),
        };
        model.addRow(data);
        tablePemetaan.setModel(model);
    }
    while(rs.next());
    }
   
    }catch(Exception e){}
    }
    
    
    
    
    
    private void tampilDataSkTanah() {
    skTanahIds.clear();
   
    try{
    String query = "SELECT * FROM`db_bapena`.`tb_dokumen` INNER JOIN `db_bapena`.`tb_status` ON (`tb_dokumen`.`id_status` = `tb_status`.`id`) WHERE id_userPemohon = '"+activeUserId+"';" ;   
    
    java.sql.Connection conn = (Connection)connection.connectionDB();
    Statement st = conn.createStatement();
    ResultSet rs = st.executeQuery(query);
    
    
    if(rs.next() == false){
    btnSuntingSK.setVisible(false);
    DefaultTableModel model2 = new DefaultTableModel();
    model2.getDataVector().removeAllElements();
    model2.fireTableDataChanged();
    model2.setRowCount(0);
    
   
    model2.addColumn("NO");
    model2.addColumn("DOKUMEN 1");
    model2.addColumn("DOKUMEN 2");
    model2.addColumn("DOKUMEN 3");
    model2.addColumn("STATUS");
    Object[] data = {
         "-" ,
         "-",
         "-",
         "-",
         "-",
        };
        model2.addRow(data);
        tableSkTanah.setModel(model2);
    }else{
    btnSuntingSK.setVisible(true);
    DefaultTableModel model = new DefaultTableModel();
    model.getDataVector().removeAllElements();
    model.fireTableDataChanged();
    model.setRowCount(0);
    
   
    model.addColumn("NO");
    model.addColumn("DOKUMEN 1");
    model.addColumn("DOKUMEN 2");
    model.addColumn("DOKUMEN 3");
    model.addColumn("STATUS");
    int no =1;
    do{
    skTanahIds.add(rs.getInt("dokumenId"));
        Object[] data = {
         no++ ,
         rs.getString("dok_satu"),
         rs.getString("dok_dua"),
         rs.getString("dok_tiga"),
         rs.getString("nama_status"),
        };
        model.addRow(data);
        tableSkTanah.setModel(model);
        
       if(rs.getString("nama_status").equals("SK Diterbitkan")){
       
       }
    }
    while(rs.next());
    }
    
    
    
    }catch(Exception e){
     System.out.println("eror disini");
    }
    
       
    }
    
}

