/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controler.connection;
import java.awt.List;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author JUNAN
 */
public class dashboardPetugas extends javax.swing.JFrame {

    /**
     * Creates new form dashboardPetugas
     */
    public ArrayList<Integer> idSkTanah = new ArrayList<Integer>();
    public ArrayList<Integer> idPermohonans = new ArrayList<Integer>();
    java.sql.Connection conn = (Connection)connection.connectionDB();
    public String activeUser;
    public int activeEmployeId;
    public int activeEmpDivId;
    
    
    public dashboardPetugas(String nameUser, int idEmploye, int idDivisi ) {
        initComponents();
        this.activeUser = nameUser;
        this.activeEmployeId = idEmploye;
        this.activeEmpDivId = idDivisi;
        txtUserHello.setText("Hallo "+nameUser);
        
        if(idDivisi == 1){
          viewTablePengukuran();  
        }
        else if(idDivisi == 2){
            swapPannel(idDivisi);
            txtPetugasPemeriksaan.setText("Hallo "+nameUser);
            viewTableSKtanah();
         
     }
       
        
        
//        System.out.println("active user name " +this.activeUser);
//        System.out.print("active user id petugas " +this.activeEmployeId);
//        System.out.print("active divisi id petugas " +this.activeEmpDivId);
        
        
    }
    
    public dashboardPetugas() {
       
        initComponents();
        swapPannel(2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bodyPanel = new javax.swing.JPanel();
        sidebarPannel = new javax.swing.JPanel();
        btnJobdesk = new javax.swing.JPanel();
        lblhome = new javax.swing.JLabel();
        btnAbout = new javax.swing.JLabel();
        btnLogout = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        btnExit = new javax.swing.JLabel();
        mainPanels = new javax.swing.JPanel();
        uiPetugasUkur = new javax.swing.JPanel();
        btnAcceptPengukuran = new javax.swing.JLabel();
        btnRejectPengukuran = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txtUserHello = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePengukuran = new javax.swing.JTable();
        btnInputHasilPengukuran = new javax.swing.JLabel();
        btnDetailPengukuran = new javax.swing.JLabel();
        btnRefeshPengukuran = new javax.swing.JLabel();
        uiPetugasPemeriksaan = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        txtPetugasPemeriksaan = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableSkTanah = new javax.swing.JTable();
        btnUbahStatusPengajuan = new javax.swing.JLabel();
        btnDetailPemeriksaan = new javax.swing.JLabel();
        btnRefreshPemeriksaan = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        bodyPanel.setMinimumSize(new java.awt.Dimension(1074, 660));
        bodyPanel.setName(""); // NOI18N

        sidebarPannel.setBackground(new java.awt.Color(21, 28, 82));
        sidebarPannel.setPreferredSize(new java.awt.Dimension(319, 660));
        sidebarPannel.setRequestFocusEnabled(false);
        sidebarPannel.setVerifyInputWhenFocusTarget(false);

        btnJobdesk.setBackground(new java.awt.Color(59, 79, 207));
        btnJobdesk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnJobdesk.setPreferredSize(new java.awt.Dimension(218, 59));
        btnJobdesk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnJobdeskMouseClicked(evt);
            }
        });
        btnJobdesk.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblhome.setFont(new java.awt.Font("Montserrat Medium", 0, 18)); // NOI18N
        lblhome.setForeground(new java.awt.Color(241, 245, 248));
        lblhome.setText("Jobdesk");
        lblhome.setToolTipText("");
        lblhome.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblhome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblhomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblhomeMouseEntered(evt);
            }
        });
        btnJobdesk.add(lblhome, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        btnAbout.setBackground(new java.awt.Color(155, 156, 172));
        btnAbout.setFont(new java.awt.Font("Montserrat Medium", 0, 16)); // NOI18N
        btnAbout.setForeground(new java.awt.Color(155, 156, 172));
        btnAbout.setText("About");
        btnAbout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAbout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAboutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAboutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAboutMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAboutMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnAboutMouseReleased(evt);
            }
        });

        btnLogout.setFont(new java.awt.Font("Montserrat Medium", 0, 16)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(155, 156, 172));
        btnLogout.setText("Logout");
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLogoutMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnLogoutMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnLogoutMouseReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Montserrat Medium", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(155, 156, 172));
        jLabel4.setText(" |");

        jLabel7.setFont(new java.awt.Font("Montserrat", 1, 22)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(242, 242, 242));
        jLabel7.setText("BADAN");

        jLabel8.setFont(new java.awt.Font("Montserrat", 1, 22)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(242, 242, 242));
        jLabel8.setText("PERTANAHAN");

        jLabel9.setFont(new java.awt.Font("Montserrat", 1, 22)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(242, 242, 242));
        jLabel9.setText("NASIONAL BATAM");

        javax.swing.GroupLayout sidebarPannelLayout = new javax.swing.GroupLayout(sidebarPannel);
        sidebarPannel.setLayout(sidebarPannelLayout);
        sidebarPannelLayout.setHorizontalGroup(
            sidebarPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarPannelLayout.createSequentialGroup()
                .addGroup(sidebarPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sidebarPannelLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(sidebarPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnJobdesk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)))
                    .addGroup(sidebarPannelLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(btnAbout)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLogout)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        sidebarPannelLayout.setVerticalGroup(
            sidebarPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarPannelLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(156, 156, 156)
                .addComponent(btnJobdesk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 217, Short.MAX_VALUE)
                .addGroup(sidebarPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAbout, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52))
        );

        jPanel2.setBackground(new java.awt.Color(241, 245, 248));
        jPanel2.setMinimumSize(new java.awt.Dimension(755, 660));
        jPanel2.setVerifyInputWhenFocusTarget(false);

        headerPanel.setBackground(new java.awt.Color(241, 245, 248));
        headerPanel.setPreferredSize(new java.awt.Dimension(755, 660));

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/closeBtn.png"))); // NOI18N
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExitMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnExitMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnExitMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        mainPanels.setBackground(new java.awt.Color(241, 245, 248));
        mainPanels.setLayout(new java.awt.CardLayout());

        uiPetugasUkur.setBackground(new java.awt.Color(241, 245, 248));

        btnAcceptPengukuran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/btnAccept.png"))); // NOI18N
        btnAcceptPengukuran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAcceptPengukuranMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAcceptPengukuranMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAcceptPengukuranMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAcceptPengukuranMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnAcceptPengukuranMouseReleased(evt);
            }
        });

        btnRejectPengukuran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/btnReject.png"))); // NOI18N
        btnRejectPengukuran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRejectPengukuranMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRejectPengukuranMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRejectPengukuranMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnRejectPengukuranMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnRejectPengukuranMouseReleased(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(232, 237, 248));
        jPanel4.setMinimumSize(new java.awt.Dimension(755, 102));
        jPanel4.setName(""); // NOI18N

        txtUserHello.setFont(new java.awt.Font("Montserrat Medium", 1, 30)); // NOI18N
        txtUserHello.setForeground(new java.awt.Color(83, 87, 122));
        txtUserHello.setText("Halo");

        jLabel21.setFont(new java.awt.Font("Montserrat Medium", 0, 13)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(120, 122, 145));
        jLabel21.setText("lorem ipsum");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(txtUserHello))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(txtUserHello)
                .addGap(0, 0, 0)
                .addComponent(jLabel21)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));

        tablePengukuran.setBackground(new java.awt.Color(255, 255, 255));
        tablePengukuran.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        tablePengukuran.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        tablePengukuran.setForeground(new java.awt.Color(122, 124, 147));
        tablePengukuran.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"01", "Jonshon", "1234321", "Batam center", "Unverified"},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "NO", "PEMOHON", "NIK", "LOKASI", "STATUS"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tablePengukuran.setGridColor(new java.awt.Color(255, 255, 255));
        tablePengukuran.setRowHeight(35);
        tablePengukuran.setSelectionBackground(new java.awt.Color(71, 86, 119));
        tablePengukuran.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tablePengukuran.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tablePengukuran);
        if (tablePengukuran.getColumnModel().getColumnCount() > 0) {
            tablePengukuran.getColumnModel().getColumn(0).setResizable(false);
            tablePengukuran.getColumnModel().getColumn(0).setPreferredWidth(2);
            tablePengukuran.getColumnModel().getColumn(1).setResizable(false);
            tablePengukuran.getColumnModel().getColumn(2).setResizable(false);
            tablePengukuran.getColumnModel().getColumn(3).setResizable(false);
            tablePengukuran.getColumnModel().getColumn(4).setResizable(false);
            tablePengukuran.getColumnModel().getColumn(4).setPreferredWidth(10);
        }

        btnInputHasilPengukuran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/btnInputPengukuran.png"))); // NOI18N
        btnInputHasilPengukuran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInputHasilPengukuranMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnInputHasilPengukuranMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnInputHasilPengukuranMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnInputHasilPengukuranMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnInputHasilPengukuranMouseReleased(evt);
            }
        });

        btnDetailPengukuran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/btnDetail.png"))); // NOI18N
        btnDetailPengukuran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDetailPengukuranMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDetailPengukuranMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDetailPengukuranMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnDetailPengukuranMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnDetailPengukuranMouseReleased(evt);
            }
        });

        btnRefeshPengukuran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/btnRefresh.png"))); // NOI18N
        btnRefeshPengukuran.setToolTipText("");
        btnRefeshPengukuran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRefeshPengukuranMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRefeshPengukuranMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRefeshPengukuranMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnRefeshPengukuranMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnRefeshPengukuranMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout uiPetugasUkurLayout = new javax.swing.GroupLayout(uiPetugasUkur);
        uiPetugasUkur.setLayout(uiPetugasUkurLayout);
        uiPetugasUkurLayout.setHorizontalGroup(
            uiPetugasUkurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, uiPetugasUkurLayout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addGroup(uiPetugasUkurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(uiPetugasUkurLayout.createSequentialGroup()
                        .addComponent(btnRefeshPengukuran)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDetailPengukuran)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnInputHasilPengukuran))
                    .addGroup(uiPetugasUkurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(uiPetugasUkurLayout.createSequentialGroup()
                            .addComponent(btnRejectPengukuran)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnAcceptPengukuran))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        uiPetugasUkurLayout.setVerticalGroup(
            uiPetugasUkurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(uiPetugasUkurLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(uiPetugasUkurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRejectPengukuran)
                    .addComponent(btnAcceptPengukuran, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(uiPetugasUkurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRefeshPengukuran)
                    .addComponent(btnDetailPengukuran)
                    .addComponent(btnInputHasilPengukuran))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        mainPanels.add(uiPetugasUkur, "card3");

        uiPetugasPemeriksaan.setBackground(new java.awt.Color(241, 245, 248));

        jPanel8.setBackground(new java.awt.Color(232, 237, 248));
        jPanel8.setMinimumSize(new java.awt.Dimension(755, 102));
        jPanel8.setName(""); // NOI18N

        txtPetugasPemeriksaan.setFont(new java.awt.Font("Montserrat Medium", 1, 30)); // NOI18N
        txtPetugasPemeriksaan.setForeground(new java.awt.Color(83, 87, 122));
        txtPetugasPemeriksaan.setText("Hallo");

        jLabel23.setFont(new java.awt.Font("Montserrat Medium", 0, 13)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(120, 122, 145));
        jLabel23.setText("Lorem ipsum dolor sin amet");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addComponent(txtPetugasPemeriksaan))
                .addContainerGap(529, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(txtPetugasPemeriksaan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel23)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jScrollPane3.setForeground(new java.awt.Color(255, 255, 255));

        tableSkTanah.setBackground(new java.awt.Color(255, 255, 255));
        tableSkTanah.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        tableSkTanah.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        tableSkTanah.setForeground(new java.awt.Color(122, 124, 147));
        tableSkTanah.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"01", "jonshon", "dok1.png", "dok2.png", "dok3", "Pemeriksaan"},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "NO", "PEMOHON", "DOKUMEN 1", "DOKUMEN 2", "DOKUMEN 3", "STATUS"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableSkTanah.setGridColor(new java.awt.Color(255, 255, 255));
        tableSkTanah.setRowHeight(35);
        tableSkTanah.setSelectionBackground(new java.awt.Color(71, 86, 119));
        tableSkTanah.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tableSkTanah.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(tableSkTanah);

        btnUbahStatusPengajuan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/btnUbahStatusPengajuan.png"))); // NOI18N
        btnUbahStatusPengajuan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUbahStatusPengajuanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUbahStatusPengajuanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUbahStatusPengajuanMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnUbahStatusPengajuanMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnUbahStatusPengajuanMouseReleased(evt);
            }
        });

        btnDetailPemeriksaan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/btnDetail.png"))); // NOI18N
        btnDetailPemeriksaan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDetailPemeriksaanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDetailPemeriksaanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDetailPemeriksaanMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnDetailPemeriksaanMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnDetailPemeriksaanMouseReleased(evt);
            }
        });

        btnRefreshPemeriksaan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/btnRefresh.png"))); // NOI18N
        btnRefreshPemeriksaan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRefreshPemeriksaanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRefreshPemeriksaanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRefreshPemeriksaanMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnRefreshPemeriksaanMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnRefreshPemeriksaanMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout uiPetugasPemeriksaanLayout = new javax.swing.GroupLayout(uiPetugasPemeriksaan);
        uiPetugasPemeriksaan.setLayout(uiPetugasPemeriksaanLayout);
        uiPetugasPemeriksaanLayout.setHorizontalGroup(
            uiPetugasPemeriksaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, uiPetugasPemeriksaanLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(uiPetugasPemeriksaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(uiPetugasPemeriksaanLayout.createSequentialGroup()
                        .addComponent(btnRefreshPemeriksaan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDetailPemeriksaan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnUbahStatusPengajuan))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 668, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );
        uiPetugasPemeriksaanLayout.setVerticalGroup(
            uiPetugasPemeriksaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, uiPetugasPemeriksaanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(uiPetugasPemeriksaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUbahStatusPengajuan)
                    .addComponent(btnRefreshPemeriksaan)
                    .addComponent(btnDetailPemeriksaan))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        mainPanels.add(uiPetugasPemeriksaan, "card4");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mainPanels, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(mainPanels, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout bodyPanelLayout = new javax.swing.GroupLayout(bodyPanel);
        bodyPanel.setLayout(bodyPanelLayout);
        bodyPanelLayout.setHorizontalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyPanelLayout.createSequentialGroup()
                .addComponent(sidebarPannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        bodyPanelLayout.setVerticalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidebarPannel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblhomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblhomeMouseClicked
        // TODO add your handling code here:
        btnJobdesk.setBackground(new java.awt.Color(59,79,207));
      
        //panel swap
       

    }//GEN-LAST:event_lblhomeMouseClicked

    private void lblhomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblhomeMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_lblhomeMouseEntered

    private void btnAboutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAboutMouseEntered
        // TODO add your handling code here:
        btnAbout.setForeground(new java.awt.Color(217,218,222));
    }//GEN-LAST:event_btnAboutMouseEntered

    private void btnAboutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAboutMouseExited
        // TODO add your handling code here:
        btnAbout.setForeground(new java.awt.Color(155,156,172));
    }//GEN-LAST:event_btnAboutMouseExited

    private void btnAboutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAboutMousePressed
        // TODO add your handling code here:
        btnAbout.setForeground(new java.awt.Color(240,240,241));
    }//GEN-LAST:event_btnAboutMousePressed

    private void btnAboutMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAboutMouseReleased
        // TODO add your handling code here:
        btnAbout.setForeground(new java.awt.Color(155,156,172));
    }//GEN-LAST:event_btnAboutMouseReleased

    private void btnLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new login().setVisible(true);
    }//GEN-LAST:event_btnLogoutMouseClicked

    private void btnLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseEntered
        // TODO add your handling code here:
        btnLogout.setForeground(new java.awt.Color(217,218,222));
    }//GEN-LAST:event_btnLogoutMouseEntered

    private void btnLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseExited
        // TODO add your handling code here:
        btnLogout.setForeground(new java.awt.Color(155,156,172));
    }//GEN-LAST:event_btnLogoutMouseExited

    private void btnLogoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMousePressed
        // TODO add your handling code here:
        btnLogout.setForeground(new java.awt.Color(240,240,241));
    }//GEN-LAST:event_btnLogoutMousePressed

    private void btnLogoutMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseReleased
        // TODO add your handling code here:
        btnLogout.setForeground(new java.awt.Color(155,156,172));
    }//GEN-LAST:event_btnLogoutMouseReleased

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExitMouseClicked

    private void btnExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseEntered
        // TODO add your handling code here:
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/closeBtnHover.png")));
    }//GEN-LAST:event_btnExitMouseEntered

    private void btnExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseExited
        // TODO add your handling code here:
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/closeBtn.png")));
    }//GEN-LAST:event_btnExitMouseExited

    private void btnExitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMousePressed
        // TODO add your handling code here:
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/closeBtnPressed.png")));
    }//GEN-LAST:event_btnExitMousePressed

    private void btnExitMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseReleased
        // TODO add your handling code here:
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/closeBtn.png")));
    }//GEN-LAST:event_btnExitMouseReleased

    private void btnJobdeskMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnJobdeskMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnJobdeskMouseClicked

    private void btnRejectPengukuranMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRejectPengukuranMouseEntered
        // TODO add your handling code here:
         btnRejectPengukuran.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/btnRejectHover.png")));
    }//GEN-LAST:event_btnRejectPengukuranMouseEntered

    private void btnRejectPengukuranMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRejectPengukuranMouseExited
        // TODO add your handling code here:
        btnRejectPengukuran.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/btnReject.png")));
    }//GEN-LAST:event_btnRejectPengukuranMouseExited

    private void btnRejectPengukuranMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRejectPengukuranMousePressed
        // TODO add your handling code here:
        btnRejectPengukuran.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/btnRejectPress.png")));
    }//GEN-LAST:event_btnRejectPengukuranMousePressed

    private void btnRejectPengukuranMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRejectPengukuranMouseReleased
        // TODO add your handling code here:
        btnRejectPengukuran.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/btnReject.png")));
    }//GEN-LAST:event_btnRejectPengukuranMouseReleased

    
    
    private void btnAcceptPengukuranMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAcceptPengukuranMouseEntered
        // TODO add your handling code here:
        btnAcceptPengukuran.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/btnAcceptHover.png")));
    }//GEN-LAST:event_btnAcceptPengukuranMouseEntered

    private void btnAcceptPengukuranMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAcceptPengukuranMouseExited
        // TODO add your handling code here:
         btnAcceptPengukuran.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/btnAccept.png")));
    }//GEN-LAST:event_btnAcceptPengukuranMouseExited

    private void btnAcceptPengukuranMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAcceptPengukuranMousePressed
        // TODO add your handling code here:
         btnAcceptPengukuran.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/btnAcceptPress.png")));
    }//GEN-LAST:event_btnAcceptPengukuranMousePressed

    private void btnAcceptPengukuranMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAcceptPengukuranMouseReleased
        // TODO add your handling code here:
         btnAcceptPengukuran.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/btnAccept.png")));
    }//GEN-LAST:event_btnAcceptPengukuranMouseReleased

    private void btnInputHasilPengukuranMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInputHasilPengukuranMouseEntered
        // TODO add your handling code here:
        btnInputHasilPengukuran.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/btnInputPengukuranHover.png")));
    }//GEN-LAST:event_btnInputHasilPengukuranMouseEntered

    private void btnInputHasilPengukuranMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInputHasilPengukuranMouseExited
        // TODO add your handling code here:
        btnInputHasilPengukuran.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/btnInputPengukuran.png")));
    }//GEN-LAST:event_btnInputHasilPengukuranMouseExited

    private void btnInputHasilPengukuranMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInputHasilPengukuranMousePressed
        // TODO add your handling code here:
        btnInputHasilPengukuran.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/btnInputPengukuranPress.png")));
    }//GEN-LAST:event_btnInputHasilPengukuranMousePressed

    private void btnInputHasilPengukuranMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInputHasilPengukuranMouseReleased
        // TODO add your handling code here:
        btnInputHasilPengukuran.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/btnInputPengukuranHover.png")));
    }//GEN-LAST:event_btnInputHasilPengukuranMouseReleased

    private void btnDetailPengukuranMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDetailPengukuranMouseEntered
        // TODO add your handling code here:
        btnDetailPengukuran.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/btnDetailHover.png")));
    }//GEN-LAST:event_btnDetailPengukuranMouseEntered

    private void btnDetailPengukuranMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDetailPengukuranMouseExited
        // TODO add your handling code here:
        btnDetailPengukuran.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/btnDetail.png")));
    }//GEN-LAST:event_btnDetailPengukuranMouseExited

    private void btnDetailPengukuranMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDetailPengukuranMousePressed
        // TODO add your handling code here:
        btnDetailPengukuran.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/btnDetailPress.png")));
    }//GEN-LAST:event_btnDetailPengukuranMousePressed

    private void btnDetailPengukuranMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDetailPengukuranMouseReleased
        // TODO add your handling code here:
        btnDetailPengukuran.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/btnDetail.png")));
    }//GEN-LAST:event_btnDetailPengukuranMouseReleased

    private void btnRefeshPengukuranMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRefeshPengukuranMouseEntered
        // TODO add your handling code here:
        btnRefeshPengukuran.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/btnRefreshHover.png")));
    }//GEN-LAST:event_btnRefeshPengukuranMouseEntered

    private void btnRefeshPengukuranMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRefeshPengukuranMouseExited
        // TODO add your handling code here:
         btnRefeshPengukuran.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/btnRefresh.png")));
    }//GEN-LAST:event_btnRefeshPengukuranMouseExited

    private void btnRefeshPengukuranMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRefeshPengukuranMousePressed
        // TODO add your handling code here:
         btnRefeshPengukuran.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/btnRefreshPress.png")));
    }//GEN-LAST:event_btnRefeshPengukuranMousePressed

    private void btnRefeshPengukuranMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRefeshPengukuranMouseReleased
        // TODO add your handling code here:
         btnRefeshPengukuran.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/btnRefresh.png")));
    }//GEN-LAST:event_btnRefeshPengukuranMouseReleased

    private void btnUbahStatusPengajuanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUbahStatusPengajuanMouseEntered
        // TODO add your handling code here:
        btnUbahStatusPengajuan.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/btnUbahStatusPengajuanHover.png")));
        
    }//GEN-LAST:event_btnUbahStatusPengajuanMouseEntered

    private void btnUbahStatusPengajuanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUbahStatusPengajuanMouseExited
        // TODO add your handling code here:
        btnUbahStatusPengajuan.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/btnUbahStatusPengajuan.png")));
    }//GEN-LAST:event_btnUbahStatusPengajuanMouseExited

    private void btnUbahStatusPengajuanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUbahStatusPengajuanMousePressed
        // TODO add your handling code here:
        btnUbahStatusPengajuan.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/btnUbahStatusPengajuanPress.png")));
    }//GEN-LAST:event_btnUbahStatusPengajuanMousePressed

    private void btnUbahStatusPengajuanMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUbahStatusPengajuanMouseReleased
        // TODO add your handling code here:
        btnUbahStatusPengajuan.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/btnUbahStatusPengajuan.png")));
    }//GEN-LAST:event_btnUbahStatusPengajuanMouseReleased

    private void btnDetailPemeriksaanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDetailPemeriksaanMouseEntered
        // TODO add your handling code here:
        btnDetailPemeriksaan.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/btnDetailHover.png")));
    }//GEN-LAST:event_btnDetailPemeriksaanMouseEntered

    private void btnDetailPemeriksaanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDetailPemeriksaanMouseExited
        // TODO add your handling code here:
         btnDetailPemeriksaan.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/btnDetail.png")));
    }//GEN-LAST:event_btnDetailPemeriksaanMouseExited

    private void btnDetailPemeriksaanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDetailPemeriksaanMousePressed
        // TODO add your handling code here:
         btnDetailPemeriksaan.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/btnDetailPress.png")));
    }//GEN-LAST:event_btnDetailPemeriksaanMousePressed

    private void btnDetailPemeriksaanMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDetailPemeriksaanMouseReleased
        // TODO add your handling code here:
         btnDetailPemeriksaan.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/btnDetail.png")));
    }//GEN-LAST:event_btnDetailPemeriksaanMouseReleased

    private void btnRefreshPemeriksaanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRefreshPemeriksaanMouseEntered
        // TODO add your handling code here:
         btnRefreshPemeriksaan.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/btnRefreshHover.png")));
    }//GEN-LAST:event_btnRefreshPemeriksaanMouseEntered

    private void btnRefreshPemeriksaanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRefreshPemeriksaanMouseExited
        // TODO add your handling code here:
         btnRefreshPemeriksaan.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/btnRefresh.png")));
    }//GEN-LAST:event_btnRefreshPemeriksaanMouseExited

    private void btnRefreshPemeriksaanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRefreshPemeriksaanMousePressed
        // TODO add your handling code here:
         btnRefreshPemeriksaan.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/btnRefreshPress.png")));
    }//GEN-LAST:event_btnRefreshPemeriksaanMousePressed

    private void btnRefreshPemeriksaanMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRefreshPemeriksaanMouseReleased
        // TODO add your handling code here:
         btnRefreshPemeriksaan.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/btnRefresh.png")));
    }//GEN-LAST:event_btnRefreshPemeriksaanMouseReleased

    private void btnAcceptPengukuranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAcceptPengukuranMouseClicked
        // TODO add your handling code here:
       
        
          if(tablePengukuran.getSelectionModel().isSelectionEmpty()){
            JOptionPane.showMessageDialog(this, "Harap Pilih baris berkas terlebih dahulu!","Eror", JOptionPane.WARNING_MESSAGE);
         }
          else{
              acceptPengukuran(idPermohonans.get(tablePengukuran.getSelectedRow()));
          }
       
        
    }//GEN-LAST:event_btnAcceptPengukuranMouseClicked

    private void btnRejectPengukuranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRejectPengukuranMouseClicked
        // TODO add your handling code here:
        if(tablePengukuran.getSelectionModel().isSelectionEmpty()){
            JOptionPane.showMessageDialog(this, "Harap Pilih baris berkas terlebih dahulu!","Eror", JOptionPane.WARNING_MESSAGE);
         }
          else{
              rejectPengukuran(idPermohonans.get(tablePengukuran.getSelectedRow()));
          }
    }//GEN-LAST:event_btnRejectPengukuranMouseClicked

    private void btnRefeshPengukuranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRefeshPengukuranMouseClicked
        // TODO add your handling code here:
        viewTablePengukuran();
    }//GEN-LAST:event_btnRefeshPengukuranMouseClicked

    private void btnDetailPengukuranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDetailPengukuranMouseClicked
        // TODO add your handling code here:
         if(tablePengukuran.getSelectionModel().isSelectionEmpty()){
            JOptionPane.showMessageDialog(this, "Harap Pilih baris berkas yang ingin anda tampilkan","Eror", JOptionPane.WARNING_MESSAGE);
         }else{
            viewTablePermohonan view = new viewTablePermohonan(idPermohonans.get(tablePengukuran.getSelectedRow()));
             view.setVisible(true);}
    }//GEN-LAST:event_btnDetailPengukuranMouseClicked

    private void btnInputHasilPengukuranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInputHasilPengukuranMouseClicked
        // TODO add your handling code here:
        if(tablePengukuran.getSelectionModel().isSelectionEmpty()){
            JOptionPane.showMessageDialog(this, "Harap Pilih baris berkas yang ingin anda tampilkan","Eror", JOptionPane.WARNING_MESSAGE);
         }else{
            inputHasilPengukuran view = new inputHasilPengukuran(idPermohonans.get(tablePengukuran.getSelectedRow()),activeEmployeId );
             view.setVisible(true);}
    }//GEN-LAST:event_btnInputHasilPengukuranMouseClicked

    private void btnRefreshPemeriksaanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRefreshPemeriksaanMouseClicked
        // TODO add your handling code here:
        viewTableSKtanah();
    }//GEN-LAST:event_btnRefreshPemeriksaanMouseClicked

    private void btnDetailPemeriksaanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDetailPemeriksaanMouseClicked
        // TODO add your handling code here:
         if(tableSkTanah.getSelectionModel().isSelectionEmpty()){
            JOptionPane.showMessageDialog(this, "Harap Pilih baris berkas yang ingin anda tampilkan","Eror", JOptionPane.WARNING_MESSAGE);
         }else{
//             viewDetailSkTanah view = new viewDetailSkTanah(idSkTanah.get(tableSkTanah.getSelectedRow()));
viewDetailSkTanah view = new viewDetailSkTanah(idSkTanah.get(tableSkTanah.getSelectedRow()));
             view.setVisible(true);}
    }//GEN-LAST:event_btnDetailPemeriksaanMouseClicked

    private void btnUbahStatusPengajuanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUbahStatusPengajuanMouseClicked
        // TODO add your handling code here:
        if(tableSkTanah.getSelectionModel().isSelectionEmpty()){
            JOptionPane.showMessageDialog(this, "Harap Pilih baris berkas yang ingin anda tampilkan","Eror", JOptionPane.WARNING_MESSAGE);
         }else{
//             viewDetailSkTanah view = new viewDetailSkTanah(idSkTanah.get(tableSkTanah.getSelectedRow()));
       formUbahStatus view = new formUbahStatus(idSkTanah.get(tableSkTanah.getSelectedRow()), activeEmployeId);
             view.setVisible(true);}
        
    }//GEN-LAST:event_btnUbahStatusPengajuanMouseClicked

    private void btnAboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAboutMouseClicked
        // TODO add your handling code here:
        about abt = new about();
        abt.setVisible(true);
    }//GEN-LAST:event_btnAboutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboardPetugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboardPetugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboardPetugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboardPetugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboardPetugas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JLabel btnAbout;
    private javax.swing.JLabel btnAcceptPengukuran;
    private javax.swing.JLabel btnDetailPemeriksaan;
    private javax.swing.JLabel btnDetailPengukuran;
    private javax.swing.JLabel btnExit;
    private javax.swing.JLabel btnInputHasilPengukuran;
    private javax.swing.JPanel btnJobdesk;
    private javax.swing.JLabel btnLogout;
    private javax.swing.JLabel btnRefeshPengukuran;
    private javax.swing.JLabel btnRefreshPemeriksaan;
    private javax.swing.JLabel btnRejectPengukuran;
    private javax.swing.JLabel btnUbahStatusPengajuan;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblhome;
    private javax.swing.JPanel mainPanels;
    private javax.swing.JPanel sidebarPannel;
    private javax.swing.JTable tablePengukuran;
    private javax.swing.JTable tableSkTanah;
    private javax.swing.JLabel txtPetugasPemeriksaan;
    private javax.swing.JLabel txtUserHello;
    private javax.swing.JPanel uiPetugasPemeriksaan;
    private javax.swing.JPanel uiPetugasUkur;
    // End of variables declaration//GEN-END:variables

private void swapPannel(int idDivisi){

if(idDivisi == 2){
        mainPanels.removeAll();
        mainPanels.repaint();
        mainPanels.revalidate();
        
        mainPanels.add(uiPetugasPemeriksaan);
     
        mainPanels.repaint();
        mainPanels.revalidate();  
}
}



private void viewTablePengukuran(){
//tablePengukuran

idPermohonans.clear();
try{
    String query = "SELECT * FROM `db_bapena`.`tb_permohonan` INNER JOIN `db_bapena`.`tb_status` ON (`tb_permohonan`.`status` = `tb_status`.`id`) WHERE id_petugas = '"+activeEmployeId+"' AND `tb_permohonan`.`status` NOT IN (3,4,5,6,7,9);" ;   
    
    Statement st = conn.createStatement();
    ResultSet rs = st.executeQuery(query);
    
    
    if(rs.next() == false){
        btnDetailPengukuran.setVisible(false);
        btnRejectPengukuran.setVisible(false);
        btnAcceptPengukuran.setVisible(false);
    DefaultTableModel model2 = new DefaultTableModel();
    model2.getDataVector().removeAllElements();
    model2.fireTableDataChanged();
    model2.setRowCount(0);
    
   
    model2.addColumn("NO");
    model2.addColumn("PEMOHON");
    model2.addColumn("NIK");
    model2.addColumn("LOKASI");
    model2.addColumn("STATUS");
    
    Object[] data = {
         "-",
         "-",
         "-",
         "-",
         "-"};
        model2.addRow(data);
        tablePengukuran.setModel(model2);  
    }else{
        btnDetailPengukuran.setVisible(true);
        btnRejectPengukuran.setVisible(true);
        btnAcceptPengukuran.setVisible(true);
        DefaultTableModel model = new DefaultTableModel();
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        model.setRowCount(0);
    
   
        model.addColumn("NO");
        model.addColumn("PEMOHON");
        model.addColumn("NIK");
        model.addColumn("LOKASI");
        model.addColumn("STATUS");

        int no =1;
        do{
         idPermohonans.add(rs.getInt("idPermohonan"));
            Object[] data = {
             no++ ,
             rs.getString("nama"),
             rs.getString("nik"),
             rs.getString("lokasi_tnh"),
             rs.getString("nama_status"),
            };
            model.addRow(data);
            tablePengukuran.setModel(model); }
         
        while (rs.next());
    }
    }catch(Exception e){
    JOptionPane.showMessageDialog(rootPane, e);
    }
    }




private void viewTableSKtanah(){
//tablePengukuran
idSkTanah.clear();
try{
    String query = "SELECT * FROM `db_bapena`.`tb_dokumen` INNER JOIN `db_bapena`.`tb_users` ON (`tb_dokumen`.`id_userPemohon` = `tb_users`.`id_users`) INNER JOIN `db_bapena`.`tb_status` ON (`tb_dokumen`.`id_status` = `tb_status`.`id`) WHERE id_petugasPemeriksaan = '"+activeEmployeId+"' AND id_status NOT IN (1,2,3,7,9);" ;   
    
    Statement st = conn.createStatement();
    ResultSet rs = st.executeQuery(query);
    
    
    if(rs.next() == false){
    btnDetailPemeriksaan.setVisible(false);
    btnUbahStatusPengajuan.setVisible(false);
    DefaultTableModel model2 = new DefaultTableModel();
    model2.getDataVector().removeAllElements();
    model2.fireTableDataChanged();
    model2.setRowCount(0);
    
   
    model2.addColumn("NO");
    model2.addColumn("PEMOHON");
    model2.addColumn("DOKUMEN 1");
    model2.addColumn("DOKUMEN 2");
    model2.addColumn("DOKUMEN 3");
    model2.addColumn("STATUS");
    
    Object[] data = {
         "-",
         "-",
         "-",
         "-",
         "-",
         "-"};
        model2.addRow(data);
        tableSkTanah.setModel(model2);   
        
    }
    else{
     btnDetailPemeriksaan.setVisible(true);
     btnUbahStatusPengajuan.setVisible(true);
    DefaultTableModel model = new DefaultTableModel();
    model.getDataVector().removeAllElements();
    model.fireTableDataChanged();
    model.setRowCount(0);
    
   
    model.addColumn("NO");
    model.addColumn("PEMOHON");
    model.addColumn("DOKUMEN 1");
    model.addColumn("DOKUMEN 2");
    model.addColumn("DOKUMEN 3");
    model.addColumn("STATUS");
    
    int no =1;
    do{
    idSkTanah.add(rs.getInt("dokumenId"));
    Object[] data = {
     no++ ,
     rs.getString("name"),
     rs.getString("dok_satu"),
     rs.getString("dok_dua"),
     rs.getString("dok_tiga"),
     rs.getString("nama_status"),
     };
        model.addRow(data);
        tableSkTanah.setModel(model);}
    
    while(rs.next());
    
    }
    }catch(Exception e){
     JOptionPane.showMessageDialog(rootPane, e);
    }
    }

private void acceptPengukuran(int permohonanId){
try{

               String queryubahStatusJob = "UPDATE tb_petugas SET jobStatus=1 where idPetugas="+activeEmployeId+"";
               String queryInsert = "UPDATE tb_permohonan SET status=?  WHERE idPermohonan = '"+permohonanId+"';";
               
               java.sql.PreparedStatement pstm = conn.prepareStatement(queryInsert);
               pstm.setInt(1, 2);
               pstm.executeUpdate();
               
               java.sql.PreparedStatement ubahStatus = conn.prepareStatement(queryInsert);
               ubahStatus.executeUpdate();
               
               JOptionPane.showMessageDialog(null, "Data telah berhasil diubah!");
}
catch(Exception e){
    System.out.println("ErorOnAccUkur");
}
}


private void rejectPengukuran(int permohonanId){
    
    try{  
               String queryubahStatusJob = "UPDATE tb_petugas SET jobStatus=0 WHERE idPetugas="+activeEmployeId+"";
               String queryInsert = "UPDATE tb_permohonan SET status=?  WHERE idPermohonan = '"+permohonanId+"';";
               
               java.sql.PreparedStatement pstm = conn.prepareStatement(queryInsert);
               pstm.setInt(1, 9);
               pstm.executeUpdate();
               
               java.sql.PreparedStatement ubahStatus = conn.prepareStatement(queryubahStatusJob);
               ubahStatus.executeUpdate();
               
               JOptionPane.showMessageDialog(null, "Data telah berhasil diubah!");
}
    catch(Exception e){
    System.out.println("ErorOnRjctUkur");}
}



}



