/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controler.connection;
import java.sql.Connection;
import javax.swing.JOptionPane;

/**
 *
 * @author JUNAN
 */
public class formUbahStatus extends javax.swing.JFrame {

    /**
     * Creates new form formUbahStatus
     */
    
    private int selectedStats;
    private int permohonanId;
    private int idPetugas;
    
    public formUbahStatus(int idPermohonan,int idPetugass) {
        initComponents();
       this.permohonanId = idPermohonan;
       this.idPetugas = idPetugass;
       System.out.println("id permohonan = "+idPermohonan);
       
    }
    
    
    public formUbahStatus() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        statusGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        rb1 = new javax.swing.JRadioButton();
        rb2 = new javax.swing.JRadioButton();
        rb3 = new javax.swing.JRadioButton();
        rb4 = new javax.swing.JRadioButton();
        btnKirim = new javax.swing.JLabel();
        btnExit = new javax.swing.JLabel();
        btnBatal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        rb1.setBackground(new java.awt.Color(255, 255, 255));
        statusGroup.add(rb1);
        rb1.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        rb1.setForeground(new java.awt.Color(51, 51, 51));
        rb1.setText("Pemeriksaan Selesai");

        statusGroup.add(rb2);
        rb2.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        rb2.setForeground(new java.awt.Color(51, 51, 51));
        rb2.setText("Proses Penerbitan SK");

        statusGroup.add(rb3);
        rb3.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        rb3.setForeground(new java.awt.Color(51, 51, 51));
        rb3.setText("SK Diterbitkan");

        statusGroup.add(rb4);
        rb4.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        rb4.setForeground(new java.awt.Color(51, 51, 51));
        rb4.setText("Permohonan Ditolak");

        btnKirim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/btnKirim.png"))); // NOI18N
        btnKirim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKirimMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnKirimMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnKirimMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnKirimMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnKirimMouseReleased(evt);
            }
        });

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/closeBtn.png"))); // NOI18N
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExitMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnExitMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnExitMouseReleased(evt);
            }
        });

        btnBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/btnBatal.png"))); // NOI18N
        btnBatal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBatalMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBatalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBatalMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnBatalMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnBatalMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btnKirim)
                            .addGap(107, 107, 107))
                        .addComponent(btnBatal))
                    .addComponent(rb3)
                    .addComponent(rb2)
                    .addComponent(rb1)
                    .addComponent(rb4))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rb1)
                .addGap(18, 18, 18)
                .addComponent(rb2)
                .addGap(18, 18, 18)
                .addComponent(rb3)
                .addGap(18, 18, 18)
                .addComponent(rb4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnKirim)
                    .addComponent(btnBatal))
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        // TODO add your handling code here:

        this.dispose();
    }//GEN-LAST:event_btnExitMouseClicked

    private void btnExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseEntered
        // TODO add your handling code here:
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/closeBtnHover.png")));
    }//GEN-LAST:event_btnExitMouseEntered

    private void btnExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseExited
        // TODO add your handling code here:
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/closeBtn.png")));
    }//GEN-LAST:event_btnExitMouseExited

    private void btnExitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMousePressed
        // TODO add your handling code here:
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/closeBtnPressed.png")));
    }//GEN-LAST:event_btnExitMousePressed

    private void btnExitMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseReleased
        // TODO add your handling code here:
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/closeBtn.png")));
    }//GEN-LAST:event_btnExitMouseReleased

    private void btnKirimMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKirimMouseEntered
        // TODO add your handling code here:
        btnKirim.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/btnKirimHover.png")));
        
    }//GEN-LAST:event_btnKirimMouseEntered

    private void btnKirimMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKirimMouseExited
        // TODO add your handling code here:
        btnKirim.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/btnKirim.png")));
    }//GEN-LAST:event_btnKirimMouseExited

    private void btnKirimMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKirimMousePressed
        // TODO add your handling code here:
        btnKirim.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/btnKirimPress.png")));
    }//GEN-LAST:event_btnKirimMousePressed

    private void btnKirimMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKirimMouseReleased
        // TODO add your handling code here:
        btnKirim.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/btnKirimHover.png")));
    }//GEN-LAST:event_btnKirimMouseReleased

    private void btnBatalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBatalMouseEntered
        // TODO add your handling code here:
        btnBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/btnBatalHover.png")));
    }//GEN-LAST:event_btnBatalMouseEntered

    private void btnBatalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBatalMouseExited
        // TODO add your handling code here:
        btnBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/btnBatal.png")));
    }//GEN-LAST:event_btnBatalMouseExited

    private void btnBatalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBatalMousePressed
        // TODO add your handling code here:
        btnBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/btnBatalPress.png")));
    }//GEN-LAST:event_btnBatalMousePressed

    private void btnBatalMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBatalMouseReleased
        // TODO add your handling code here:
        btnBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/btnBatal.png")));
    }//GEN-LAST:event_btnBatalMouseReleased

    private void btnKirimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKirimMouseClicked
        // TODO add your handling code here:
        
        if(rb1.isSelected()){
            selectedStats = 5;
            ubahStats();
            this.dispose();
        }
        else if(rb2.isSelected()){
            selectedStats = 6;
            ubahStats();
            this.dispose();
        }
        else if(rb3.isSelected()){
            selectedStats = 7;
            ubahStats();
            changeJobStatsPetugas();
            this.dispose();
        }
        else if(rb4.isSelected()){
            selectedStats = 9;
            ubahStats();
            changeJobStatsPetugas();
            this.dispose();
        }else{
        JOptionPane.showMessageDialog(null, "Anda belum memilih!");
        }
        
        
      
        
        
        
        
        
    }//GEN-LAST:event_btnKirimMouseClicked

    private void btnBatalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBatalMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnBatalMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formUbahStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formUbahStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formUbahStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formUbahStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formUbahStatus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBatal;
    private javax.swing.JLabel btnExit;
    private javax.swing.JLabel btnKirim;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rb1;
    private javax.swing.JRadioButton rb2;
    private javax.swing.JRadioButton rb3;
    private javax.swing.JRadioButton rb4;
    private javax.swing.ButtonGroup statusGroup;
    // End of variables declaration//GEN-END:variables

    java.sql.Connection conn = (Connection)connection.connectionDB();
private void ubahStats(){

    String sql = "UPDATE tb_dokumen SET id_status="+selectedStats+" WHERE dokumenId = '"+permohonanId+"';";
    try{    
        
     
    java.sql.PreparedStatement ptsm = conn.prepareStatement(sql);
    ptsm.executeUpdate();
    JOptionPane.showMessageDialog(null, "Data Berhasil di ubah!");
    
    
    
}
catch(Exception e){
System.out.println("setViewText eror");
}
}

private void changeJobStatsPetugas(){
    try{
    String queryubahStatusJob = "UPDATE tb_petugas SET jobStatus=0 where idPetugas= '"+idPetugas+"'";
    java.sql.PreparedStatement ubahStatus = conn.prepareStatement(queryubahStatusJob);
    ubahStatus.executeUpdate();
    }
    catch(Exception e){
    System.out.println("changeJobStatEror");
    }
    

}
}
