/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controler.connection;
import java.awt.Image;
import java.io.File;
import java.nio.file.Files;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author JUNAN
 */
public class formPengajuanSK extends javax.swing.JFrame {

    /**
     * Creates new form formPermohonanPengukuran
     */
    String fileNameDok1;
    String fileNameDok2;
    String fileNameDok3;
    
    public String activeUser ;
    public int idUserPemohon ;
    public formPengajuanSK(String nameUser,int idUser){
        initComponents();
        this.activeUser = nameUser;
        this.idUserPemohon = idUser;
        System.out.println("active user name " +this.activeUser);
        System.out.print("active user id pemohon " +this.idUserPemohon);
    }
    
    public formPengajuanSK() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblNama2 = new javax.swing.JLabel();
        lblNama5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnPilihDok1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        imgDok2 = new javax.swing.JLabel();
        btnPilihDok2 = new javax.swing.JLabel();
        btnPilihDok3 = new javax.swing.JLabel();
        lblNama1 = new javax.swing.JLabel();
        lblNama3 = new javax.swing.JLabel();
        lblNama4 = new javax.swing.JLabel();
        btnBatal = new javax.swing.JLabel();
        btnKirim = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        imgDok1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        imgDok3 = new javax.swing.JLabel();
        btnExit = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Montserrat SemiBold", 1, 25)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Form Pengajuan");

        jLabel2.setBackground(new java.awt.Color(51, 51, 51));
        jLabel2.setFont(new java.awt.Font("Montserrat SemiBold", 1, 25)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("SK Tanah");

        lblNama2.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        lblNama2.setForeground(new java.awt.Color(102, 102, 102));
        lblNama2.setText("Pastikan anda telah melakukan tahap pengukuran dan");

        lblNama5.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        lblNama5.setForeground(new java.awt.Color(102, 102, 102));
        lblNama5.setText("melampirkan dokumen pendukung seperti surat ukur");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel2))
                        .addComponent(lblNama2, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblNama5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNama2)
                .addGap(0, 0, 0)
                .addComponent(lblNama5, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        btnPilihDok1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/btnPilihFile.png"))); // NOI18N
        btnPilihDok1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPilihDok1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPilihDok1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPilihDok1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPilihDok1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnPilihDok1MouseReleased(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(241, 245, 248));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(imgDok2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(imgDok2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnPilihDok2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/btnPilihFile.png"))); // NOI18N
        btnPilihDok2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPilihDok2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPilihDok2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPilihDok2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPilihDok2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnPilihDok2MouseReleased(evt);
            }
        });

        btnPilihDok3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/btnPilihFile.png"))); // NOI18N
        btnPilihDok3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPilihDok3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPilihDok3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPilihDok3MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPilihDok3MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnPilihDok3MouseReleased(evt);
            }
        });

        lblNama1.setFont(new java.awt.Font("Montserrat Medium", 0, 10)); // NOI18N
        lblNama1.setForeground(new java.awt.Color(102, 102, 102));
        lblNama1.setText("Dokumen 1");

        lblNama3.setFont(new java.awt.Font("Montserrat Medium", 0, 10)); // NOI18N
        lblNama3.setForeground(new java.awt.Color(102, 102, 102));
        lblNama3.setText("Dokumen 2");

        lblNama4.setFont(new java.awt.Font("Montserrat Medium", 0, 10)); // NOI18N
        lblNama4.setForeground(new java.awt.Color(102, 102, 102));
        lblNama4.setText("Dokumen 3");

        btnBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/btnBatal.png"))); // NOI18N
        btnBatal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBatal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBatalMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBatalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBatalMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnBatalMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnBatalMouseReleased(evt);
            }
        });

        btnKirim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/btnKirim.png"))); // NOI18N
        btnKirim.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnKirim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKirimMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnKirimMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnKirimMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnKirimMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnKirimMouseReleased(evt);
            }
        });

        jPanel7.setBackground(new java.awt.Color(241, 245, 248));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(imgDok1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(imgDok1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(241, 245, 248));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(imgDok3, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(imgDok3, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(btnPilihDok1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPilihDok2)
                        .addGap(118, 118, 118)
                        .addComponent(btnPilihDok3)
                        .addGap(50, 50, 50))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(431, 431, 431)
                        .addComponent(btnKirim)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBatal)
                        .addGap(6, 6, 6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNama1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNama3, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lblNama4, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(55, 55, 55))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblNama1)
                        .addComponent(lblNama3))
                    .addComponent(lblNama4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 6, Short.MAX_VALUE)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPilihDok2)
                    .addComponent(btnPilihDok3)
                    .addComponent(btnPilihDok1))
                .addGap(76, 76, 76)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnKirim)
                    .addComponent(btnBatal))
                .addGap(29, 29, 29))
        );

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/closeBtn.png"))); // NOI18N
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExitMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnExitMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnExitMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        // TODO add your handling code here:
       this.dispose();
    }//GEN-LAST:event_btnExitMouseClicked

    private void btnExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseEntered
        // TODO add your handling code here:
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/closeBtnHover.png")));
    }//GEN-LAST:event_btnExitMouseEntered

    private void btnExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseExited
        // TODO add your handling code here:
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/closeBtn.png")));
    }//GEN-LAST:event_btnExitMouseExited

    private void btnExitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMousePressed
        // TODO add your handling code here:
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/closeBtnPressed.png")));
    }//GEN-LAST:event_btnExitMousePressed

    private void btnExitMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseReleased
        // TODO add your handling code here:
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/closeBtn.png")));
    }//GEN-LAST:event_btnExitMouseReleased

    
//    btnBatal Behavior
    private void btnBatalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBatalMouseEntered
        // TODO add your handling code here:
        btnBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/btnBatalHover.png")));
    }//GEN-LAST:event_btnBatalMouseEntered

    private void btnBatalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBatalMouseExited
        // TODO add your handling code here:
        btnBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/btnBatal.png")));
    }//GEN-LAST:event_btnBatalMouseExited

    private void btnBatalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBatalMousePressed
        // TODO add your handling code here:
        btnBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/btnBatalPress.png")));
    }//GEN-LAST:event_btnBatalMousePressed

    private void btnBatalMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBatalMouseReleased
        // TODO add your handling code here:
         btnBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/btnBatal.png")));
    }//GEN-LAST:event_btnBatalMouseReleased

    
    //behavior btnKirim
    private void btnKirimMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKirimMouseEntered
        // TODO add your handling code here:
        btnKirim.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/btnKirimHover.png")));
    }//GEN-LAST:event_btnKirimMouseEntered

    private void btnKirimMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKirimMouseExited
        // TODO add your handling code here:
         btnKirim.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/btnKirim.png")));
    }//GEN-LAST:event_btnKirimMouseExited

    private void btnKirimMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKirimMousePressed
        // TODO add your handling code here:
         btnKirim.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/btnKirimPress.png")));
    }//GEN-LAST:event_btnKirimMousePressed

    private void btnKirimMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKirimMouseReleased
        // TODO add your handling code here:
         btnKirim.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/btnKirim.png")));
    }//GEN-LAST:event_btnKirimMouseReleased

    private void btnBatalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBatalMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnBatalMouseClicked

    private void btnKirimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKirimMouseClicked
        // TODO add your handling code here:
        
        addPermohonan();
        this.dispose();
       
    }//GEN-LAST:event_btnKirimMouseClicked

    
    
    private void btnPilihDok1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPilihDok1MouseEntered
        // TODO add your handling code here:
        btnPilihDok1.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/btnPilihFileHover.png")));
    }//GEN-LAST:event_btnPilihDok1MouseEntered

    private void btnPilihDok1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPilihDok1MouseExited
        // TODO add your handling code here:
         btnPilihDok1.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/btnPilihFile.png")));
    }//GEN-LAST:event_btnPilihDok1MouseExited

    private void btnPilihDok1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPilihDok1MousePressed
        // TODO add your handling code here:
         btnPilihDok1.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/btnPilihFilePress.png")));
    }//GEN-LAST:event_btnPilihDok1MousePressed

    private void btnPilihDok1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPilihDok1MouseReleased
        // TODO add your handling code here:
         btnPilihDok1.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/btnPilihFile.png")));
    }//GEN-LAST:event_btnPilihDok1MouseReleased

    private void btnPilihDok1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPilihDok1MouseClicked
        // TODO add your handling code here:
        
        try{
            JFileChooser choser = new JFileChooser();
            choser.showOpenDialog(null);
            File f = choser.getSelectedFile();
            ImageIcon icon = new ImageIcon(f.toString());
            Image image = icon.getImage().getScaledInstance(imgDok1.getWidth(),imgDok1.getHeight(), Image.SCALE_SMOOTH); 
            ImageIcon ic = new ImageIcon(image);
            imgDok1.setIcon(ic);
            
            fileNameDok1 = f.getAbsolutePath();
         
            //ini kalau mau save ke dokumen ke dalam folder project trus di rename name nya sesuai format
//            String newpath = "src/Upload/dokumen";
//            File directory = new File (newpath);
//            
//            if(!directory.exists()){
//            directory.mkdirs();
//            }
//            
//            File sourceFile = null;
//            File destinationFile = null;
//            
//            
//            String extension = fileNameDok1.substring(fileNameDok1.lastIndexOf(".")+ 1);
//            sourceFile = new File(fileNameDok1);
//            Date tanggal_update = new Date();
//            String tampilan = "yyyyMMdd";
//            SimpleDateFormat fm =  new SimpleDateFormat(tampilan);
//            String tanggal = String.valueOf(fm.format(tanggal_update));
//            destinationFile = new File(newpath,activeUser+"Dokumen1_"+tanggal.toString()+"."+extension);
//            
//            
//            Files.copy(sourceFile.toPath(), destinationFile.toPath());
            
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"eror upload "+e);
        }
    }//GEN-LAST:event_btnPilihDok1MouseClicked

    
    
    
    
    private void btnPilihDok2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPilihDok2MouseEntered
        // TODO add your handling code here:
         btnPilihDok2.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/btnPilihFileHover.png")));
    }//GEN-LAST:event_btnPilihDok2MouseEntered

    private void btnPilihDok2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPilihDok2MouseExited
        // TODO add your handling code here:
        btnPilihDok2.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/btnPilihFile.png")));
    }//GEN-LAST:event_btnPilihDok2MouseExited

    private void btnPilihDok2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPilihDok2MousePressed
        // TODO add your handling code here:
        btnPilihDok2.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/btnPilihFilePress.png")));
    }//GEN-LAST:event_btnPilihDok2MousePressed

    private void btnPilihDok2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPilihDok2MouseReleased
        // TODO add your handling code here:
        btnPilihDok2.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/btnPilihFile.png")));
    }//GEN-LAST:event_btnPilihDok2MouseReleased

    private void btnPilihDok2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPilihDok2MouseClicked
        // TODO add your handling code here:
        
         try{
            JFileChooser choser = new JFileChooser();
            choser.showOpenDialog(null);
            File f = choser.getSelectedFile();
            ImageIcon icon = new ImageIcon(f.toString());
            Image image = icon.getImage().getScaledInstance(imgDok2.getWidth(),imgDok2.getHeight(), Image.SCALE_SMOOTH); 
            ImageIcon ic = new ImageIcon(image);
            imgDok2.setIcon(ic);
            
            fileNameDok2 = f.getAbsolutePath();
            
            }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"eror upload "+e);
        }
        
    }//GEN-LAST:event_btnPilihDok2MouseClicked

    
    
    
    private void btnPilihDok3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPilihDok3MouseEntered
        // TODO add your handling code here:
        btnPilihDok3.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/btnPilihFileHover.png")));
    }//GEN-LAST:event_btnPilihDok3MouseEntered

    private void btnPilihDok3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPilihDok3MouseExited
        // TODO add your handling code here:
        btnPilihDok3.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/btnPilihFile.png")));
    }//GEN-LAST:event_btnPilihDok3MouseExited

    private void btnPilihDok3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPilihDok3MousePressed
        // TODO add your handling code here:
        btnPilihDok3.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/btnPilihFilePress.png")));
    }//GEN-LAST:event_btnPilihDok3MousePressed

    private void btnPilihDok3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPilihDok3MouseReleased
        // TODO add your handling code here:
         btnPilihDok3.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/btnPilihFile.png")));
    }//GEN-LAST:event_btnPilihDok3MouseReleased

    private void btnPilihDok3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPilihDok3MouseClicked
        // TODO add your handling code here:
         try{
            JFileChooser choser = new JFileChooser();
            choser.showOpenDialog(null);
            File f = choser.getSelectedFile();
            ImageIcon icon = new ImageIcon(f.toString());
            Image image = icon.getImage().getScaledInstance(imgDok3.getWidth(),imgDok3.getHeight(), Image.SCALE_SMOOTH); 
            ImageIcon ic = new ImageIcon(image);
            imgDok3.setIcon(ic);
            
            fileNameDok3 = f.getAbsolutePath();
            
            }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"eror upload "+e);
        }
    }//GEN-LAST:event_btnPilihDok3MouseClicked

    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formPengajuanSK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formPengajuanSK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formPengajuanSK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formPengajuanSK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formPengajuanSK().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBatal;
    private javax.swing.JLabel btnExit;
    private javax.swing.JLabel btnKirim;
    private javax.swing.JLabel btnPilihDok1;
    private javax.swing.JLabel btnPilihDok2;
    private javax.swing.JLabel btnPilihDok3;
    private javax.swing.JLabel imgDok1;
    private javax.swing.JLabel imgDok2;
    private javax.swing.JLabel imgDok3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel lblNama1;
    private javax.swing.JLabel lblNama2;
    private javax.swing.JLabel lblNama3;
    private javax.swing.JLabel lblNama4;
    private javax.swing.JLabel lblNama5;
    // End of variables declaration//GEN-END:variables

 java.sql.Connection conn = (Connection)connection.connectionDB();
     private void addPermohonan() {
          try{
           if(fileNameDok1 == "" || fileNameDok2 == "" || fileNameDok3 == "" ) {
            JOptionPane.showMessageDialog(this, "Dokumen Tidak Boleh Kosong!\nHarap melengkapi dokumen", "Pesan", JOptionPane.WARNING_MESSAGE);
           
        }
           else{
               String query = "INSERT INTO tb_dokumen (dok_satu, dok_dua, dok_tiga, id_petugasPemeriksaan, id_userPemohon, id_status) VALUES (?, ? , ? , ?, ?, ?);";
               
               
               
               java.sql.PreparedStatement pstm = conn.prepareStatement(query);
               pstm.setString(1, fileNameDok1);
               pstm.setString(2, fileNameDok2);
               pstm.setString(3, fileNameDok3);
               pstm.setInt(4, randomPetugasPemeriksaan());
               pstm.setInt(5, idUserPemohon);
               pstm.setInt(6, 4);
           
               
               pstm.executeUpdate();
               JOptionPane.showMessageDialog(null, "permohonan telah dikirm\n selalu cek status pengajuan SK tanah anda\n apabila telah diterbitkan maka silahkan mengunjungi kantor terdekat!");
                          
           }
        }
        catch(Exception e){
           JOptionPane.showMessageDialog(rootPane, e);
        }
          }



    
    private int randomPetugasPemeriksaan(){
   int id_petugas = 0;
       try{
        String queryubahStatusJob = "UPDATE tb_petugas SET jobStatus=1 where idPetugas=?";
        String queryRandPetugas = "SELECT * FROM tb_petugas WHERE idDivisi = 2 AND jobStatus = false ORDER BY RAND() LIMIT 1;";
        
        Connection con = (Connection)connection.connectionDB();
        //random
        Statement st = con.createStatement();
        ResultSet rsRand = st.executeQuery(queryRandPetugas);
        //ubah status random
        java.sql.PreparedStatement ubahStatusJob = con.prepareStatement(queryubahStatusJob);
        
          if(rsRand.next()){
           id_petugas = rsRand.getInt("idPetugas");
           ubahStatusJob.setInt(1, rsRand.getInt("idPetugas"));
           ubahStatusJob.executeUpdate();
          }else{
           JOptionPane.showMessageDialog(rootPane, "eror randFucntion", "Pesan",JOptionPane.ERROR_MESSAGE);
           
           }
       }
        catch(Exception e){
         JOptionPane.showMessageDialog(rootPane, e);
        }
     return id_petugas; 
    }
    
    
    
}
