/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import controler.connection;

import javax.swing.Icon;
import javax.swing.ImageIcon;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;


/**
 *
 * @author JUNAN
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
  
    public login() {
        initComponents();
        clearTxtFieldLogin();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnExit = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ilustration = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        form = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblNamaPengguna = new javax.swing.JLabel();
        lblKataSandi = new javax.swing.JLabel();
        btnMasuk = new javax.swing.JPanel();
        labelBtnMasuk = new javax.swing.JLabel();
        labelDaftar = new javax.swing.JLabel();
        btnDaftar = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(938, 528));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(938, 528));
        jPanel1.setMinimumSize(new java.awt.Dimension(938, 528));
        jPanel1.setPreferredSize(new java.awt.Dimension(938, 528));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/closeBtn.png"))); // NOI18N
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExitMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnExitMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnExitMouseReleased(evt);
            }
        });
        jPanel1.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 10, 30, 30));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 60));

        ilustration.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/ilustration.png"))); // NOI18N
        jLabel1.setToolTipText("");

        javax.swing.GroupLayout ilustrationLayout = new javax.swing.GroupLayout(ilustration);
        ilustration.setLayout(ilustrationLayout);
        ilustrationLayout.setHorizontalGroup(
            ilustrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ilustrationLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        ilustrationLayout.setVerticalGroup(
            ilustrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ilustrationLayout.createSequentialGroup()
                .addContainerGap(96, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
        );

        jPanel1.add(ilustration, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 400, -1));

        form.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Ebrima", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(67, 67, 67));
        jLabel2.setText("BADAN");

        jLabel3.setFont(new java.awt.Font("Ebrima", 1, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(67, 67, 67));
        jLabel3.setText("PERTANAHAN");

        jLabel4.setFont(new java.awt.Font("Ebrima", 1, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(67, 67, 67));
        jLabel4.setText("NASIONAL BATAM");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/accent.png"))); // NOI18N

        lblNamaPengguna.setForeground(new java.awt.Color(57, 57, 57));
        lblNamaPengguna.setText("Nama Pengguna");

        lblKataSandi.setForeground(new java.awt.Color(57, 57, 57));
        lblKataSandi.setText("Kata Sandi");

        btnMasuk.setBackground(new java.awt.Color(68, 70, 233));
        btnMasuk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMasuk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMasukMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMasukMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMasukMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMasukMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnMasukMouseReleased(evt);
            }
        });

        labelBtnMasuk.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        labelBtnMasuk.setForeground(new java.awt.Color(255, 255, 255));
        labelBtnMasuk.setText("Masuk");

        javax.swing.GroupLayout btnMasukLayout = new javax.swing.GroupLayout(btnMasuk);
        btnMasuk.setLayout(btnMasukLayout);
        btnMasukLayout.setHorizontalGroup(
            btnMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(btnMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnMasukLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(labelBtnMasuk)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        btnMasukLayout.setVerticalGroup(
            btnMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 53, Short.MAX_VALUE)
            .addGroup(btnMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnMasukLayout.createSequentialGroup()
                    .addGap(0, 17, Short.MAX_VALUE)
                    .addComponent(labelBtnMasuk)
                    .addGap(0, 17, Short.MAX_VALUE)))
        );

        labelDaftar.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        labelDaftar.setForeground(new java.awt.Color(57, 57, 57));
        labelDaftar.setText("Belum mempunyai akun?");

        btnDaftar.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        btnDaftar.setForeground(new java.awt.Color(68, 70, 233));
        btnDaftar.setText("Daftar sekarang!");
        btnDaftar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDaftar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDaftarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDaftarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDaftarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnDaftarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnDaftarMouseReleased(evt);
            }
        });

        txtUsername.setBackground(new java.awt.Color(255, 255, 255));
        txtUsername.setFont(new java.awt.Font("Ebrima", 0, 24)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(143, 143, 143));
        txtUsername.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(155, 155, 155)));
        txtUsername.setCaretColor(new java.awt.Color(155, 155, 155));
        txtUsername.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });

        txtPassword.setBackground(new java.awt.Color(255, 255, 255));
        txtPassword.setFont(new java.awt.Font("Ebrima", 0, 24)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(143, 143, 143));
        txtPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(155, 155, 155)));
        txtPassword.setCaretColor(new java.awt.Color(155, 155, 155));

        javax.swing.GroupLayout formLayout = new javax.swing.GroupLayout(form);
        form.setLayout(formLayout);
        formLayout.setHorizontalGroup(
            formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formLayout.createSequentialGroup()
                .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formLayout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(labelDaftar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDaftar))
                    .addGroup(formLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                            .addComponent(lblKataSandi, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(lblNamaPengguna, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMasuk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE))))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        formLayout.setVerticalGroup(
            formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)))
                .addComponent(lblNamaPengguna)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblKataSandi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDaftar)
                    .addComponent(btnDaftar))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jPanel1.add(form, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 6, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void clearTxtFieldLogin(){
    txtUsername.setText("");
    txtPassword.setText("");
    txtUsername.setEnabled(true);
    txtPassword.setEnabled(true);
    }
    
    
    private void cekLogin(){
        
        try{
            if(txtUsername.getText().equals("") || txtPassword.getPassword().equals("")){
            JOptionPane.showMessageDialog(this, "Data Tidak Boleh Kosong", "Pesan", JOptionPane.ERROR_MESSAGE);
            clearTxtFieldLogin();
            txtUsername.requestFocus();
            }else{
                 Connection con = (Connection)connection.connectionDB();
                 Statement st = con.createStatement();
                 Statement st2 = con.createStatement();
                 String query = ("SELECT * FROM `db_bapena`.`tb_users`  WHERE username = '"+txtUsername.getText()+"'  AND `tb_users`.`password` = '"+String.valueOf(txtPassword.getPassword())+"';") ;
                 String query2 = ("SELECT * FROM `db_bapena`.`tb_users`  INNER JOIN `db_bapena`.`tb_petugas` ON (`tb_users`.`id_petugas` = `tb_petugas`.`idPetugas`) WHERE `tb_users`.`username` = '"+txtUsername.getText()+"'  AND `tb_users`.`password` = '"+String.valueOf(txtPassword.getPassword())+"';");
                 ResultSet rs = st.executeQuery(query);
                 ResultSet rs2 = st2.executeQuery(query2);
                 if(rs.next()){  
                        
                    if(("3".equals(rs.getString("level"))) ){
                    this.dispose();
                    new dashboardUser(rs.getString("name"), rs.getInt("id_users")).setVisible(true);          
                    
                    }else if(("1".equals(rs.getString("level"))) ){
                     this.dispose();
                     new dashboardAdmin(rs.getString("name"),rs.getInt("id_users")).setVisible(true);
                     
                    }else if(rs2.next()){
                        if(("2".equals(rs2.getString("level")))){
                        this.dispose();
                        new dashboardPetugas(rs2.getString("name"),rs2.getInt("id_petugas"),rs2.getInt("idDivisi")).setVisible(true);
                        }
                      }
                    
                 }else{
                   JOptionPane.showMessageDialog(rootPane, "Username dan Password Salah\nAtau Akun Belum Terdaftar", "Pesan",JOptionPane.ERROR_MESSAGE);
                   clearTxtFieldLogin();      
                 }
           }
    }
        catch(Exception e){
        System.out.println("error");
        }
        
    }
    
    //behavior button masuk
    private void btnMasukMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMasukMouseEntered
        // TODO add your handling code here:
        btnMasuk.setBackground(new java.awt.Color(55,56,208));
       
    }//GEN-LAST:event_btnMasukMouseEntered

    private void btnMasukMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMasukMouseExited
        // TODO add your handling code here:
        btnMasuk.setBackground(new java.awt.Color(68,70,217));
        
    }//GEN-LAST:event_btnMasukMouseExited

    private void btnMasukMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMasukMousePressed
        // TODO add your handling code here:
         btnMasuk.setBackground(new java.awt.Color(48,50,187));
    }//GEN-LAST:event_btnMasukMousePressed

    private void btnMasukMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMasukMouseReleased
        // TODO add your handling code here:
        btnMasuk.setBackground(new java.awt.Color(68,70,233));
    }//GEN-LAST:event_btnMasukMouseReleased

    
    //behavior buton daftar
    private void btnDaftarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDaftarMouseEntered
        // TODO add your handling code here:
        btnDaftar.setForeground(new java.awt.Color(48,50,187));
    }//GEN-LAST:event_btnDaftarMouseEntered

    private void btnDaftarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDaftarMouseExited
        // TODO add your handling code here:
        btnDaftar.setForeground(new java.awt.Color(68,70,217));
    }//GEN-LAST:event_btnDaftarMouseExited

    private void btnDaftarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDaftarMousePressed
        // TODO add your handling code here:
         btnDaftar.setForeground(new java.awt.Color(39,41,156));
    }//GEN-LAST:event_btnDaftarMousePressed

    private void btnDaftarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDaftarMouseReleased
        // TODO add your handling code here:
        btnDaftar.setForeground(new java.awt.Color(68,70,233));
    }//GEN-LAST:event_btnDaftarMouseReleased

    
    //behavior btnExit
    private void btnExitMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseReleased
        // TODO add your handling code here:
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/closeBtn.png")));
    }//GEN-LAST:event_btnExitMouseReleased

    //behavior btnExit
    private void btnExitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMousePressed
        // TODO add your handling code here:
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/closeBtnPressed.png")));
    }//GEN-LAST:event_btnExitMousePressed

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExitMouseClicked

    private void btnExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseEntered
        // TODO add your handling code here:
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/closeBtnHover.png")));
    }//GEN-LAST:event_btnExitMouseEntered

    private void btnExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseExited
        // TODO add your handling code here:
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/closeBtn.png")));
    }//GEN-LAST:event_btnExitMouseExited

    private void btnDaftarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDaftarMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new register().setVisible(true);
    }//GEN-LAST:event_btnDaftarMouseClicked

    private void btnMasukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMasukMouseClicked
        // TODO add your handling code here:
        cekLogin();
    }//GEN-LAST:event_btnMasukMouseClicked

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnDaftar;
    private javax.swing.JLabel btnExit;
    private javax.swing.JPanel btnMasuk;
    private javax.swing.JPanel form;
    private javax.swing.JPanel ilustration;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelBtnMasuk;
    private javax.swing.JLabel labelDaftar;
    private javax.swing.JLabel lblKataSandi;
    private javax.swing.JLabel lblNamaPengguna;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
