/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controler.connection;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author JUNAN
 */
public class SuntingFormPermohonanPengukuran extends javax.swing.JFrame {

    /**
     * Creates new form formPermohonanPengukuran
     */
    public int idPermohonan ;
    
    
    public SuntingFormPermohonanPengukuran(int idUser){
        initComponents();
         
         
        
        this.idPermohonan = idUser;
        setViewText();
    }
    public SuntingFormPermohonanPengukuran() {
        initComponents();
         setViewText();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblNama1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtNama = new javax.swing.JTextField();
        lblNama = new javax.swing.JLabel();
        lblNik = new javax.swing.JLabel();
        txtNIK = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblNohp = new javax.swing.JLabel();
        txtNohp = new javax.swing.JTextField();
        lblAlamat = new javax.swing.JLabel();
        txtAlamat = new javax.swing.JTextField();
        lblLokasi = new javax.swing.JLabel();
        txtLokasi = new javax.swing.JTextField();
        lblBukti = new javax.swing.JLabel();
        txtBukti = new javax.swing.JTextField();
        lblUkuran = new javax.swing.JLabel();
        txtUkuran = new javax.swing.JTextField();
        lblKoordinat = new javax.swing.JLabel();
        txtKoordinat = new javax.swing.JTextField();
        lblTambahan = new javax.swing.JLabel();
        txtTambahan = new javax.swing.JTextField();
        btnKirim = new javax.swing.JLabel();
        btnBatal = new javax.swing.JLabel();
        btnExit = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Montserrat SemiBold", 1, 25)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Sunting Data Form");

        jLabel2.setBackground(new java.awt.Color(51, 51, 51));
        jLabel2.setFont(new java.awt.Font("Montserrat SemiBold", 1, 25)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Pengukuran Tanah");

        lblNama1.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        lblNama1.setForeground(new java.awt.Color(102, 102, 102));
        lblNama1.setText("Harap berhati-hati dalam mengisi!");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNama1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(16, 16, 16))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNama1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        txtNama.setBackground(new java.awt.Color(255, 255, 255));
        txtNama.setFont(new java.awt.Font("Ebrima", 0, 24)); // NOI18N
        txtNama.setForeground(new java.awt.Color(143, 143, 143));
        txtNama.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(155, 155, 155)));
        txtNama.setCaretColor(new java.awt.Color(155, 155, 155));
        txtNama.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });

        lblNama.setForeground(new java.awt.Color(57, 57, 57));
        lblNama.setText("Nama Lengkap");

        lblNik.setForeground(new java.awt.Color(57, 57, 57));
        lblNik.setText("NIK");

        txtNIK.setBackground(new java.awt.Color(255, 255, 255));
        txtNIK.setFont(new java.awt.Font("Ebrima", 0, 24)); // NOI18N
        txtNIK.setForeground(new java.awt.Color(143, 143, 143));
        txtNIK.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(155, 155, 155)));
        txtNIK.setCaretColor(new java.awt.Color(155, 155, 155));
        txtNIK.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtNIK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNIKActionPerformed(evt);
            }
        });

        lblEmail.setForeground(new java.awt.Color(57, 57, 57));
        lblEmail.setText("Email");

        txtEmail.setBackground(new java.awt.Color(255, 255, 255));
        txtEmail.setFont(new java.awt.Font("Ebrima", 0, 24)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(143, 143, 143));
        txtEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(155, 155, 155)));
        txtEmail.setCaretColor(new java.awt.Color(155, 155, 155));
        txtEmail.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        lblNohp.setForeground(new java.awt.Color(57, 57, 57));
        lblNohp.setText("No Telepon");

        txtNohp.setBackground(new java.awt.Color(255, 255, 255));
        txtNohp.setFont(new java.awt.Font("Ebrima", 0, 24)); // NOI18N
        txtNohp.setForeground(new java.awt.Color(143, 143, 143));
        txtNohp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(155, 155, 155)));
        txtNohp.setCaretColor(new java.awt.Color(155, 155, 155));
        txtNohp.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtNohp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNohpActionPerformed(evt);
            }
        });

        lblAlamat.setForeground(new java.awt.Color(57, 57, 57));
        lblAlamat.setText("Alamat");

        txtAlamat.setBackground(new java.awt.Color(255, 255, 255));
        txtAlamat.setFont(new java.awt.Font("Ebrima", 0, 24)); // NOI18N
        txtAlamat.setForeground(new java.awt.Color(143, 143, 143));
        txtAlamat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(155, 155, 155)));
        txtAlamat.setCaretColor(new java.awt.Color(155, 155, 155));
        txtAlamat.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtAlamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlamatActionPerformed(evt);
            }
        });

        lblLokasi.setForeground(new java.awt.Color(57, 57, 57));
        lblLokasi.setText("Lokasi Tanah");

        txtLokasi.setBackground(new java.awt.Color(255, 255, 255));
        txtLokasi.setFont(new java.awt.Font("Ebrima", 0, 24)); // NOI18N
        txtLokasi.setForeground(new java.awt.Color(143, 143, 143));
        txtLokasi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(155, 155, 155)));
        txtLokasi.setCaretColor(new java.awt.Color(155, 155, 155));
        txtLokasi.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtLokasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLokasiActionPerformed(evt);
            }
        });

        lblBukti.setForeground(new java.awt.Color(57, 57, 57));
        lblBukti.setText("Bukti Kepemilikan");

        txtBukti.setBackground(new java.awt.Color(255, 255, 255));
        txtBukti.setFont(new java.awt.Font("Ebrima", 0, 24)); // NOI18N
        txtBukti.setForeground(new java.awt.Color(143, 143, 143));
        txtBukti.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(155, 155, 155)));
        txtBukti.setCaretColor(new java.awt.Color(155, 155, 155));
        txtBukti.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtBukti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuktiActionPerformed(evt);
            }
        });

        lblUkuran.setForeground(new java.awt.Color(57, 57, 57));
        lblUkuran.setText("Ukuran Tanah");

        txtUkuran.setBackground(new java.awt.Color(255, 255, 255));
        txtUkuran.setFont(new java.awt.Font("Ebrima", 0, 24)); // NOI18N
        txtUkuran.setForeground(new java.awt.Color(143, 143, 143));
        txtUkuran.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(155, 155, 155)));
        txtUkuran.setCaretColor(new java.awt.Color(155, 155, 155));
        txtUkuran.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtUkuran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUkuranActionPerformed(evt);
            }
        });

        lblKoordinat.setForeground(new java.awt.Color(57, 57, 57));
        lblKoordinat.setText("Titik Koordinat");

        txtKoordinat.setBackground(new java.awt.Color(255, 255, 255));
        txtKoordinat.setFont(new java.awt.Font("Ebrima", 0, 24)); // NOI18N
        txtKoordinat.setForeground(new java.awt.Color(143, 143, 143));
        txtKoordinat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(155, 155, 155)));
        txtKoordinat.setCaretColor(new java.awt.Color(155, 155, 155));
        txtKoordinat.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtKoordinat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKoordinatActionPerformed(evt);
            }
        });

        lblTambahan.setForeground(new java.awt.Color(57, 57, 57));
        lblTambahan.setText("Tambahan");

        txtTambahan.setBackground(new java.awt.Color(255, 255, 255));
        txtTambahan.setFont(new java.awt.Font("Ebrima", 0, 24)); // NOI18N
        txtTambahan.setForeground(new java.awt.Color(143, 143, 143));
        txtTambahan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(155, 155, 155)));
        txtTambahan.setCaretColor(new java.awt.Color(155, 155, 155));
        txtTambahan.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtTambahan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTambahanActionPerformed(evt);
            }
        });

        btnKirim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/btnKirim.png"))); // NOI18N
        btnKirim.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnKirim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKirimMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnKirimMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnKirimMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnKirimMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnKirimMouseReleased(evt);
            }
        });

        btnBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/btnBatal.png"))); // NOI18N
        btnBatal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBatal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBatalMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBatalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBatalMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnBatalMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnBatalMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnKirim)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBatal))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNohp, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNohp, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNIK, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNik, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNama, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTambahan, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTambahan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtKoordinat, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblKoordinat, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUkuran, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUkuran, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBukti, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBukti, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLokasi, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLokasi, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(43, 43, 43))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblNama)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNik)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNIK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNohp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNohp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAlamat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblLokasi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLokasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblBukti)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBukti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblUkuran)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUkuran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblKoordinat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtKoordinat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTambahan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTambahan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnKirim)
                    .addComponent(btnBatal))
                .addGap(15, 15, 15))
        );

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/closeBtn.png"))); // NOI18N
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExitMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnExitMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnExitMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void txtNIKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNIKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNIKActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtNohpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNohpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNohpActionPerformed

    private void txtAlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlamatActionPerformed

    private void txtLokasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLokasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLokasiActionPerformed

    private void txtBuktiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuktiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuktiActionPerformed

    private void txtUkuranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUkuranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUkuranActionPerformed

    private void txtKoordinatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKoordinatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKoordinatActionPerformed

    private void txtTambahanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTambahanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTambahanActionPerformed

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnExitMouseClicked

    private void btnExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseEntered
        // TODO add your handling code here:
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/closeBtnHover.png")));
    }//GEN-LAST:event_btnExitMouseEntered

    private void btnExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseExited
        // TODO add your handling code here:
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/closeBtn.png")));
    }//GEN-LAST:event_btnExitMouseExited

    private void btnExitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMousePressed
        // TODO add your handling code here:
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/closeBtnPressed.png")));
    }//GEN-LAST:event_btnExitMousePressed

    private void btnExitMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseReleased
        // TODO add your handling code here:
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/closeBtn.png")));
    }//GEN-LAST:event_btnExitMouseReleased

    
//    btnBatal Behavior
    private void btnBatalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBatalMouseEntered
        // TODO add your handling code here:
        btnBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/btnBatalHover.png")));
    }//GEN-LAST:event_btnBatalMouseEntered

    private void btnBatalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBatalMouseExited
        // TODO add your handling code here:
        btnBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/btnBatal.png")));
    }//GEN-LAST:event_btnBatalMouseExited

    private void btnBatalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBatalMousePressed
        // TODO add your handling code here:
        btnBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/btnBatalPress.png")));
    }//GEN-LAST:event_btnBatalMousePressed

    private void btnBatalMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBatalMouseReleased
        // TODO add your handling code here:
         btnBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/btnBatal.png")));
    }//GEN-LAST:event_btnBatalMouseReleased

    
    //behavior btnKirim
    private void btnKirimMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKirimMouseEntered
        // TODO add your handling code here:
        btnKirim.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/btnKirimHover.png")));
    }//GEN-LAST:event_btnKirimMouseEntered

    private void btnKirimMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKirimMouseExited
        // TODO add your handling code here:
         btnKirim.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/btnKirim.png")));
    }//GEN-LAST:event_btnKirimMouseExited

    private void btnKirimMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKirimMousePressed
        // TODO add your handling code here:
         btnKirim.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/btnKirimPress.png")));
    }//GEN-LAST:event_btnKirimMousePressed

    private void btnKirimMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKirimMouseReleased
        // TODO add your handling code here:
         btnKirim.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/btnKirim.png")));
    }//GEN-LAST:event_btnKirimMouseReleased

    private void btnBatalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBatalMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnBatalMouseClicked

    private void btnKirimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKirimMouseClicked
        // TODO add your handling code here:
        
      suntingPermohonan();
      
      this.dispose();
      
      
    }//GEN-LAST:event_btnKirimMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SuntingFormPermohonanPengukuran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SuntingFormPermohonanPengukuran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SuntingFormPermohonanPengukuran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SuntingFormPermohonanPengukuran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SuntingFormPermohonanPengukuran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBatal;
    private javax.swing.JLabel btnExit;
    private javax.swing.JLabel btnKirim;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblAlamat;
    private javax.swing.JLabel lblBukti;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblKoordinat;
    private javax.swing.JLabel lblLokasi;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblNama1;
    private javax.swing.JLabel lblNik;
    private javax.swing.JLabel lblNohp;
    private javax.swing.JLabel lblTambahan;
    private javax.swing.JLabel lblUkuran;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtBukti;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtKoordinat;
    private javax.swing.JTextField txtLokasi;
    private javax.swing.JTextField txtNIK;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNohp;
    private javax.swing.JTextField txtTambahan;
    private javax.swing.JTextField txtUkuran;
    // End of variables declaration//GEN-END:variables

//    private void resetTxtField() {
//        txtNama.setText("");
//        txtNIK.setText("");
//        txtEmail.setText("");
//        txtNohp.setText("");
//        txtAlamat.setText("");
//        txtLokasi.setText("");
//        txtBukti.setText("");
//        txtUkuran.setText("");
//        txtKoordinat.setText("");
//         }
    
    
    java.sql.Connection conn = (Connection)connection.connectionDB();
    private void setViewText() {
         String queryView = "SELECT * FROM tb_permohonan WHERE idPermohonan = '"+idPermohonan+"';";
         try{
             
          
         Statement st = conn.createStatement();
         ResultSet rs = st.executeQuery(queryView);
         if(rs.next()){
            txtNama.setText(rs.getString("nama"));
            txtNIK.setText(rs.getString("nik"));
            txtEmail.setText(rs.getString("email"));
            txtNohp.setText(rs.getString("no_telp"));
            txtAlamat.setText(rs.getString("alamat"));
            txtLokasi.setText(rs.getString("lokasi_tnh"));
            txtBukti.setText(rs.getString("bukti_milik"));
            txtUkuran.setText(rs.getString("ukuran_tnh"));
            txtKoordinat.setText(rs.getString("titik_koordinat"));
            txtTambahan.setText("");
         }
         }
         
        catch(Exception e){
            System.out.println("setViewText eror");
        }
    }
    private void suntingPermohonan() {
          try{
//               String queryInsert = "UPDATE tb_permohonan (nama, nik, email, no_telp, alamat, lokasi_tnh, bukti_milik, ukuran_tnh, titik_koordinat) VALUES (?, ? , ? , ?, ?, ?, ?, ?, ?) WHERE id_user = '"+idUserPemohon+"';";
               String queryInsert = "UPDATE tb_permohonan SET nama=?, nik=?, email=? ,no_telp=?, alamat= ?, lokasi_tnh =? , bukti_milik= ?, ukuran_tnh=?, titik_koordinat=?  WHERE idPermohonan = '"+idPermohonan+"';";
               
               java.sql.PreparedStatement pstm = conn.prepareStatement(queryInsert);
               
               pstm.setString(1, txtNama.getText());
               pstm.setString(2, txtNIK.getText());
               pstm.setString(3, txtEmail.getText());
               pstm.setString(4, txtNohp.getText());
               pstm.setString(5, txtAlamat.getText());
               pstm.setString(6, txtLokasi.getText());
               pstm.setString(7, txtBukti.getText());
               pstm.setString(8, txtUkuran.getText());
               pstm.setString(9, txtKoordinat.getText());
               pstm.executeUpdate();
               JOptionPane.showMessageDialog(null, "Data telah berhasil diubah!");
                       
           
        }
        catch(Exception e){
           JOptionPane.showMessageDialog(rootPane, e);
        }
          }
}
